// Code generated by mockery. DO NOT EDIT.

package notify

import (
	localize "github.com/ministryofjustice/opg-modernising-lpa/internal/localize"
	mock "github.com/stretchr/testify/mock"
)

// mockTo is an autogenerated mock type for the To type
type mockTo struct {
	mock.Mock
}

type mockTo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTo) EXPECT() *mockTo_Expecter {
	return &mockTo_Expecter{mock: &_m.Mock}
}

// ignore provides a mock function with given fields:
func (_m *mockTo) ignore() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ignore")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// mockTo_ignore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ignore'
type mockTo_ignore_Call struct {
	*mock.Call
}

// ignore is a helper method to define mock.On call
func (_e *mockTo_Expecter) ignore() *mockTo_ignore_Call {
	return &mockTo_ignore_Call{Call: _e.mock.On("ignore")}
}

func (_c *mockTo_ignore_Call) Run(run func()) *mockTo_ignore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTo_ignore_Call) Return(_a0 bool) *mockTo_ignore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTo_ignore_Call) RunAndReturn(run func() bool) *mockTo_ignore_Call {
	_c.Call.Return(run)
	return _c
}

// toEmail provides a mock function with given fields:
func (_m *mockTo) toEmail() (string, localize.Lang) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for toEmail")
	}

	var r0 string
	var r1 localize.Lang
	if rf, ok := ret.Get(0).(func() (string, localize.Lang)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() localize.Lang); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(localize.Lang)
	}

	return r0, r1
}

// mockTo_toEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'toEmail'
type mockTo_toEmail_Call struct {
	*mock.Call
}

// toEmail is a helper method to define mock.On call
func (_e *mockTo_Expecter) toEmail() *mockTo_toEmail_Call {
	return &mockTo_toEmail_Call{Call: _e.mock.On("toEmail")}
}

func (_c *mockTo_toEmail_Call) Run(run func()) *mockTo_toEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTo_toEmail_Call) Return(_a0 string, _a1 localize.Lang) *mockTo_toEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockTo_toEmail_Call) RunAndReturn(run func() (string, localize.Lang)) *mockTo_toEmail_Call {
	_c.Call.Return(run)
	return _c
}

// toMobile provides a mock function with given fields:
func (_m *mockTo) toMobile() (string, localize.Lang) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for toMobile")
	}

	var r0 string
	var r1 localize.Lang
	if rf, ok := ret.Get(0).(func() (string, localize.Lang)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() localize.Lang); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(localize.Lang)
	}

	return r0, r1
}

// mockTo_toMobile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'toMobile'
type mockTo_toMobile_Call struct {
	*mock.Call
}

// toMobile is a helper method to define mock.On call
func (_e *mockTo_Expecter) toMobile() *mockTo_toMobile_Call {
	return &mockTo_toMobile_Call{Call: _e.mock.On("toMobile")}
}

func (_c *mockTo_toMobile_Call) Run(run func()) *mockTo_toMobile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTo_toMobile_Call) Return(_a0 string, _a1 localize.Lang) *mockTo_toMobile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockTo_toMobile_Call) RunAndReturn(run func() (string, localize.Lang)) *mockTo_toMobile_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTo creates a new instance of mockTo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTo {
	mock := &mockTo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
