graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Modernising Lasting Power of Attorney - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    30("<div style='font-weight: bold'>OPG Services</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Court Ordered Severances</div>")
    style 30 fill:#999999,stroke:#6b6b6b,color:#ffffff
    31("<div style='font-weight: bold'>Scanning Software</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>TBC</div>")
    style 31 fill:#999999,stroke:#6b6b6b,color:#ffffff
    32["<div style='font-weight: bold'>Use an LPA</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Use/View an LPA Service.</div>"]
    style 32 fill:#999999,stroke:#6b6b6b,color:#ffffff

    subgraph 2 [Modernising Lasting Power of Attorney]
      style 2 fill:#ffffff,stroke:#444444,color:#444444

      12("<div style='font-weight: bold'>LPA ID Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway, Go]</div><div style='font-size: 80%; margin-top:10px'>Manages the LPA IDs.</div>")
      style 12 fill:#438dd5,stroke:#2e6295,color:#ffffff
      13[("<div style='font-weight: bold'>Registered LPA Data Store</div><div style='font-size: 70%; margin-top: 0px'>[Container: AuroraDB]</div><div style='font-size: 80%; margin-top:10px'>Stores immutable LPA data<br />with high availablility,<br />security and auditing.</div>")]
      style 13 fill:#438dd5,stroke:#2e6295,color:#ffffff
      16("<div style='font-weight: bold'>Registered LPA Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway]</div><div style='font-size: 80%; margin-top:10px'>Highly available API for<br />reading and searching the LPA<br />Register</div>")
      style 16 fill:#438dd5,stroke:#2e6295,color:#ffffff
      21("<div style='font-weight: bold'>LPA Paper Ingestion Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway, Go]</div><div style='font-size: 80%; margin-top:10px'>Handles the ingestion of the<br />Paper Journey.</div>")
      style 21 fill:#438dd5,stroke:#2e6295,color:#ffffff
      22("<div style='font-weight: bold'>Sirius Public API</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway, Go]</div><div style='font-size: 80%; margin-top:10px'>Interaction point between<br />Sirius Case Management and<br />other services.</div>")
      style 22 fill:#999999,stroke:#6b6b6b,color:#ffffff
      23("<div style='font-weight: bold'>Sirius Case Management</div><div style='font-size: 70%; margin-top: 0px'>[Container: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Case Management for case<br />working LPAs.</div>")
      style 23 fill:#85bbf0,stroke:#5d82a8,color:#000000
      3["<div style='font-weight: bold'>Make a Lasting Power of Attorney Online</div><div style='font-size: 70%; margin-top: 0px'>[Container: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Allows users to draft a<br />Lasting Power of Attorney<br />online.</div>"]
      style 3 fill:#438dd5,stroke:#2e6295,color:#ffffff
      7("<div style='font-weight: bold'>Staging Service</div><div style='font-size: 70%; margin-top: 0px'>[Container: API Gateway, Go, DynamoDB]</div><div style='font-size: 80%; margin-top:10px'>Stores and manages data for<br />pre-registration.</div>")
      style 7 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

    30-. "<div>sends data to</div><div style='font-size: 70%'></div>" .->23
    31-. "<div>sends scanned LPA Data to</div><div style='font-size: 70%'></div>" .->21
    3-. "<div>makes calls to</div><div style='font-size: 70%'></div>" .->7
    12-. "<div>gets LPA Code from</div><div style='font-size: 70%'></div>" .->7
    7-. "<div>writes validated data to</div><div style='font-size: 70%'></div>" .->16
    7-. "<div>writes case management data<br />to and read data from</div><div style='font-size: 70%'></div>" .->22
    32-. "<div>read data from</div><div style='font-size: 70%'></div>" .->22
    32-. "<div>read data from</div><div style='font-size: 70%'></div>" .->16
    16-. "<div>writes data to</div><div style='font-size: 70%'></div>" .->13
    22-. "<div>writes and read data from</div><div style='font-size: 70%'></div>" .->23
    21-. "<div>reads data from</div><div style='font-size: 70%'></div>" .->22
    21-. "<div>writes data to</div><div style='font-size: 70%'></div>" .->7
    23-. "<div>reads data from</div><div style='font-size: 70%'></div>" .->16
  end