graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Modernising Lasting Power of Attorney - Sirius Case Management - Components]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 23 [Sirius Case Management]
      style 23 fill:#ffffff,stroke:#444444,color:#444444

      24("<div style='font-weight: bold'>Sirius Internal API</div><div style='font-size: 70%; margin-top: 0px'>[Component: API Gateway, PHP]</div>")
      style 24 fill:#999999,stroke:#6b6b6b,color:#ffffff
      25[("<div style='font-weight: bold'>Sirius Database</div><div style='font-size: 70%; margin-top: 0px'>[Component: AuroraDB]</div><div style='font-size: 80%; margin-top:10px'>Stores Case Management data.</div>")]
      style 25 fill:#999999,stroke:#6b6b6b,color:#ffffff
      26("<div style='font-weight: bold'>Sirius Pre-Registered Case Management</div><div style='font-size: 70%; margin-top: 0px'>[Component: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Sirius Microservice for<br />Pre-Registered LPAs.</div>")
      style 26 fill:#85bbf0,stroke:#5d82a8,color:#000000
      27("<div style='font-weight: bold'>Sirius Registered Case Management</div><div style='font-size: 70%; margin-top: 0px'>[Component: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Sirius Microservice for<br />Registered LPAs.</div>")
      style 27 fill:#85bbf0,stroke:#5d82a8,color:#000000
      28("<div style='font-weight: bold'>Sirius Paper Channel Case Management</div><div style='font-size: 70%; margin-top: 0px'>[Component: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Sirius Microservice for Paper<br />Channel LPAs.</div>")
      style 28 fill:#85bbf0,stroke:#5d82a8,color:#000000
    end

  end