// Code generated by mockery v2.42.2. DO NOT EDIT.

package donor

import (
	context "context"

	event "github.com/ministryofjustice/opg-modernising-lpa/internal/event"
	mock "github.com/stretchr/testify/mock"
)

// mockEventClient is an autogenerated mock type for the EventClient type
type mockEventClient struct {
	mock.Mock
}

type mockEventClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEventClient) EXPECT() *mockEventClient_Expecter {
	return &mockEventClient_Expecter{mock: &_m.Mock}
}

// SendPaymentReceived provides a mock function with given fields: ctx, e
func (_m *mockEventClient) SendPaymentReceived(ctx context.Context, e event.PaymentReceived) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SendPaymentReceived")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.PaymentReceived) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEventClient_SendPaymentReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPaymentReceived'
type mockEventClient_SendPaymentReceived_Call struct {
	*mock.Call
}

// SendPaymentReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - e event.PaymentReceived
func (_e *mockEventClient_Expecter) SendPaymentReceived(ctx interface{}, e interface{}) *mockEventClient_SendPaymentReceived_Call {
	return &mockEventClient_SendPaymentReceived_Call{Call: _e.mock.On("SendPaymentReceived", ctx, e)}
}

func (_c *mockEventClient_SendPaymentReceived_Call) Run(run func(ctx context.Context, e event.PaymentReceived)) *mockEventClient_SendPaymentReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.PaymentReceived))
	})
	return _c
}

func (_c *mockEventClient_SendPaymentReceived_Call) Return(_a0 error) *mockEventClient_SendPaymentReceived_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEventClient_SendPaymentReceived_Call) RunAndReturn(run func(context.Context, event.PaymentReceived) error) *mockEventClient_SendPaymentReceived_Call {
	_c.Call.Return(run)
	return _c
}

// SendReducedFeeRequested provides a mock function with given fields: ctx, e
func (_m *mockEventClient) SendReducedFeeRequested(ctx context.Context, e event.ReducedFeeRequested) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SendReducedFeeRequested")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.ReducedFeeRequested) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEventClient_SendReducedFeeRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReducedFeeRequested'
type mockEventClient_SendReducedFeeRequested_Call struct {
	*mock.Call
}

// SendReducedFeeRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - e event.ReducedFeeRequested
func (_e *mockEventClient_Expecter) SendReducedFeeRequested(ctx interface{}, e interface{}) *mockEventClient_SendReducedFeeRequested_Call {
	return &mockEventClient_SendReducedFeeRequested_Call{Call: _e.mock.On("SendReducedFeeRequested", ctx, e)}
}

func (_c *mockEventClient_SendReducedFeeRequested_Call) Run(run func(ctx context.Context, e event.ReducedFeeRequested)) *mockEventClient_SendReducedFeeRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.ReducedFeeRequested))
	})
	return _c
}

func (_c *mockEventClient_SendReducedFeeRequested_Call) Return(_a0 error) *mockEventClient_SendReducedFeeRequested_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEventClient_SendReducedFeeRequested_Call) RunAndReturn(run func(context.Context, event.ReducedFeeRequested) error) *mockEventClient_SendReducedFeeRequested_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEventClient creates a new instance of mockEventClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEventClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEventClient {
	mock := &mockEventClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
