// Code generated by mockery v2.39.1. DO NOT EDIT.

package donor

import (
	context "context"

	actor "github.com/ministryofjustice/opg-modernising-lpa/internal/actor"

	mock "github.com/stretchr/testify/mock"

	page "github.com/ministryofjustice/opg-modernising-lpa/internal/page"
)

// mockDocumentStore is an autogenerated mock type for the DocumentStore type
type mockDocumentStore struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *mockDocumentStore) Create(_a0 context.Context, _a1 *actor.DonorProvidedDetails, _a2 string, _a3 []byte) (page.Document, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 page.Document
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *actor.DonorProvidedDetails, string, []byte) (page.Document, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *actor.DonorProvidedDetails, string, []byte) page.Document); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(page.Document)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *actor.DonorProvidedDetails, string, []byte) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *mockDocumentStore) Delete(_a0 context.Context, _a1 page.Document) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, page.Document) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteInfectedDocuments provides a mock function with given fields: _a0, _a1
func (_m *mockDocumentStore) DeleteInfectedDocuments(_a0 context.Context, _a1 page.Documents) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInfectedDocuments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, page.Documents) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: _a0
func (_m *mockDocumentStore) GetAll(_a0 context.Context) (page.Documents, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 page.Documents
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (page.Documents, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) page.Documents); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(page.Documents)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Put provides a mock function with given fields: _a0, _a1
func (_m *mockDocumentStore) Put(_a0 context.Context, _a1 page.Document) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, page.Document) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Submit provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockDocumentStore) Submit(_a0 context.Context, _a1 *actor.DonorProvidedDetails, _a2 page.Documents) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Submit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *actor.DonorProvidedDetails, page.Documents) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockDocumentStore creates a new instance of mockDocumentStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDocumentStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDocumentStore {
	mock := &mockDocumentStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
