version: 2
updates:
  - package-ecosystem: 'terraform'
    pull-request-branch-name:
      separator: "-"
    directory: "/terraform/account"
    schedule:
      interval: 'daily'
  - package-ecosystem: 'terraform'
    pull-request-branch-name:
      separator: "-"
    directory: "/terraform/environment"
    schedule:
      interval: 'daily'
  - package-ecosystem: 'gomod'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'composer'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'docker'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'pip'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'github-actions'
    pull-request-branch-name:
      separator: "-"
    directory: '/'
    schedule:
      interval: 'daily'
