coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - "*_test.go"
    - "./mocks/*"
    - "./app/internal/easyid"
  status:
    project:
      default:
        target: auto
        threshold: 25%
    patch:
      default:
        target: auto
#        we can tighten this once we decide what does/doesn't need to be included in coverage runs
        threshold: 50%
