coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - "**/*_test.go"
    - "**/enum_*.go"
    - "./cmd/event-logger/main.go"
    - "./cmd/event-received/main.go"
    - "./cmd/mlpa/main.go"
    - "./cmd/mock-notify/main.go"
    - "./cmd/mock-onelogin/main.go"
    - "./cmd/mock-os-api/main.go"
    - "./internal/identity/yoti*"
    - "./internal/notify/email.go"
    - "./internal/notify/sms.go"
    - "./internal/page/fixtures"
    - "./internal/telemetry"
    - "./mocks/*"
  status:
    project:
      default:
        target: auto
        threshold: 25%
    patch:
      default:
        target: auto
#        we can tighten this once we decide what does/doesn't need to be included in coverage runs
        threshold: 50%
