with-expecter: true
inpackage: True
dir: "{{.InterfaceDir}}"
mockname: "mock{{.InterfaceName|firstUpper}}"
outpkg: "{{.PackageName}}"
filename: "mock_{{.InterfaceName}}_test.go"
all: true
packages:
  github.com/ministryofjustice/opg-modernising-lpa/cmd/event-received:
  github.com/ministryofjustice/opg-modernising-lpa/internal/app:
  github.com/ministryofjustice/opg-modernising-lpa/internal/attorney/attorneydata:
  github.com/ministryofjustice/opg-modernising-lpa/internal/attorney/attorneypage:
  github.com/ministryofjustice/opg-modernising-lpa/internal/certificateprovider/certificateproviderdata:
  github.com/ministryofjustice/opg-modernising-lpa/internal/certificateprovider/certificateproviderpage:
  github.com/ministryofjustice/opg-modernising-lpa/internal/document:
  github.com/ministryofjustice/opg-modernising-lpa/internal/donor/donordata:
  github.com/ministryofjustice/opg-modernising-lpa/internal/donor/donorpage:
  github.com/ministryofjustice/opg-modernising-lpa/internal/dynamo:
  github.com/ministryofjustice/opg-modernising-lpa/internal/event:
  github.com/ministryofjustice/opg-modernising-lpa/internal/lambda:
  github.com/ministryofjustice/opg-modernising-lpa/internal/lpastore:
  github.com/ministryofjustice/opg-modernising-lpa/internal/notify:
  github.com/ministryofjustice/opg-modernising-lpa/internal/onelogin:
  github.com/ministryofjustice/opg-modernising-lpa/internal/page:
  github.com/ministryofjustice/opg-modernising-lpa/internal/pay:
  github.com/ministryofjustice/opg-modernising-lpa/internal/place:
  github.com/ministryofjustice/opg-modernising-lpa/internal/s3:
  github.com/ministryofjustice/opg-modernising-lpa/internal/search:
  github.com/ministryofjustice/opg-modernising-lpa/internal/secrets:
  github.com/ministryofjustice/opg-modernising-lpa/internal/sesh:
  github.com/ministryofjustice/opg-modernising-lpa/internal/sharecode:
  github.com/ministryofjustice/opg-modernising-lpa/internal/supporter:
  github.com/ministryofjustice/opg-modernising-lpa/internal/supporter/supporterdata:
  github.com/ministryofjustice/opg-modernising-lpa/internal/supporter/supporterpage:
  github.com/ministryofjustice/opg-modernising-lpa/internal/uid:
  github.com/ministryofjustice/opg-modernising-lpa/internal/validation:
