misconfigurations:
  - id: AVD-DS-0002
    paths:
      - "./lambda/create_s3_replication_job/Dockerfile"
      - "./docker/event-received/Dockerfile"
    statement: Lambda creates users with least-privilege permissions.
