version: '3.8'

services:
  app:
    build:
      target: development
    working_dir: /go/bin
    depends_on:
      - oidc-mock
    volumes:
      - ./app:/go/bin/app
      - ./web/template:/go/bin/web/template

  oidc-mock:
    container_name: oidc-mock
    image: stoplight/prism:4
    build: # Does not have M1 native / arm64 images as yet but builds fine.
      context: https://github.com/stoplightio/prism.git#v4.10.1
      dockerfile: Dockerfile
    command: 'mock -h 0.0.0.0 /tmp/OIDCSpec.yml'
    volumes:
      - ./mocks/OIDCSpec.yml:/tmp/OIDCSpec.yml:ro
    ports:
      - 7011:4010
