version: '3.8'

services:
  app:
    build:
      target: development
    working_dir: /go/bin
    depends_on:
      - sign-in-mock
      - localstack
    volumes:
      - ./app:/go/bin/app
      - ./web/template:/go/bin/web/template
