version: '3.8'

services:
  app:
    build:
      target: development
    working_dir: /go/bin
    depends_on:
      - oidc-mock
    volumes:
      - ./app:/go/bin/app
      - ./web/template:/go/bin/web/template

  oidc-mock:
    container_name: oidc-mock
    image: stoplight/prism:4
    build: # Does not have M1 native / arm64 images as yet but builds fine.
      context: https://github.com/stoplightio/prism.git#v4.10.1
      dockerfile: Dockerfile
    command: 'mock -h 0.0.0.0 /tmp/OIDCSpec.yml'
    volumes:
      - ./mocks/OIDCSpec.yml:/tmp/OIDCSpec.yml:ro
    ports:
      - "7010:4010"

# service for the nginx router that will forward /token to oidc-app
  oidc-proxy:
    container_name: oidc-proxy
    image: nginx:stable-alpine
    depends_on:
      - oidc-mock
    command: 'nginx -g "daemon off;"'
    volumes:
      - ./mocks/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "7011:5000"

# service for the /token go app
  oidc-app:
    build:
      context: ./mocks/JWTProxy
    container_name: oidc-app
    depends_on:
     - oidc-mock
    ports:
      - "7012:5060"
    environment:
      - PROXY_PORT=5060
      - PROXY_PRIVATE_KEY="/app/private_key.pem"
