version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.debug
    container_name: app-debug
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - .:/app:rw,delegated
    cap_add:
      - SYS_PTRACE
    ports:
      - "2345:2345"
