version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    ports:
      - "5050:5000"
    depends_on:
      - oidc-server-mock
    volumes:
      - ./app:/app
    command: air
