// Code generated by mockery v2.45.0. DO NOT EDIT.

package supporterpage

import (
	http "net/http"

	appcontext "github.com/ministryofjustice/opg-modernising-lpa/internal/appcontext"

	mock "github.com/stretchr/testify/mock"

	supporterdata "github.com/ministryofjustice/opg-modernising-lpa/internal/supporter/supporterdata"
)

// mockHandler is an autogenerated mock type for the Handler type
type mockHandler struct {
	mock.Mock
}

type mockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *mockHandler) EXPECT() *mockHandler_Expecter {
	return &mockHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: data, w, r, organisation, member
func (_m *mockHandler) Execute(data appcontext.Data, w http.ResponseWriter, r *http.Request, organisation *supporterdata.Organisation, member *supporterdata.Member) error {
	ret := _m.Called(data, w, r, organisation, member)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(appcontext.Data, http.ResponseWriter, *http.Request, *supporterdata.Organisation, *supporterdata.Member) error); ok {
		r0 = rf(data, w, r, organisation, member)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type mockHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - data appcontext.Data
//   - w http.ResponseWriter
//   - r *http.Request
//   - organisation *supporterdata.Organisation
//   - member *supporterdata.Member
func (_e *mockHandler_Expecter) Execute(data interface{}, w interface{}, r interface{}, organisation interface{}, member interface{}) *mockHandler_Execute_Call {
	return &mockHandler_Execute_Call{Call: _e.mock.On("Execute", data, w, r, organisation, member)}
}

func (_c *mockHandler_Execute_Call) Run(run func(data appcontext.Data, w http.ResponseWriter, r *http.Request, organisation *supporterdata.Organisation, member *supporterdata.Member)) *mockHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(appcontext.Data), args[1].(http.ResponseWriter), args[2].(*http.Request), args[3].(*supporterdata.Organisation), args[4].(*supporterdata.Member))
	})
	return _c
}

func (_c *mockHandler_Execute_Call) Return(_a0 error) *mockHandler_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockHandler_Execute_Call) RunAndReturn(run func(appcontext.Data, http.ResponseWriter, *http.Request, *supporterdata.Organisation, *supporterdata.Member) error) *mockHandler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newMockHandler creates a new instance of mockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockHandler {
	mock := &mockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
