// Code generated by "enumerator -type CertificateProviderRelationshipLength -linecomment -empty"; DO NOT EDIT.
package actor

import (
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LessThanTwoYears-1]
	_ = x[GreaterThanEqualToTwoYears-2]
	_ = x[RelationshipLengthUnknown-3]
}

const _CertificateProviderRelationshipLength_name = "lt-2-yearsgte-2-yearsunknown"

var _CertificateProviderRelationshipLength_index = [...]uint8{0, 10, 21, 28}

func (i CertificateProviderRelationshipLength) String() string {
	i -= 1
	if i >= CertificateProviderRelationshipLength(len(_CertificateProviderRelationshipLength_index)-1) {
		return "CertificateProviderRelationshipLength(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CertificateProviderRelationshipLength_name[_CertificateProviderRelationshipLength_index[i]:_CertificateProviderRelationshipLength_index[i+1]]
}

func (i CertificateProviderRelationshipLength) IsLessThanTwoYears() bool {
	return i == LessThanTwoYears
}

func (i CertificateProviderRelationshipLength) IsGreaterThanEqualToTwoYears() bool {
	return i == GreaterThanEqualToTwoYears
}

func (i CertificateProviderRelationshipLength) IsRelationshipLengthUnknown() bool {
	return i == RelationshipLengthUnknown
}

func ParseCertificateProviderRelationshipLength(s string) (CertificateProviderRelationshipLength, error) {
	switch s {
	case "lt-2-years":
		return LessThanTwoYears, nil
	case "gte-2-years":
		return GreaterThanEqualToTwoYears, nil
	case "unknown":
		return RelationshipLengthUnknown, nil
	default:
		return CertificateProviderRelationshipLength(0), fmt.Errorf("invalid CertificateProviderRelationshipLength '%s'", s)
	}
}

type CertificateProviderRelationshipLengthOptions struct {
	LessThanTwoYears           CertificateProviderRelationshipLength
	GreaterThanEqualToTwoYears CertificateProviderRelationshipLength
	RelationshipLengthUnknown  CertificateProviderRelationshipLength
}

var CertificateProviderRelationshipLengthValues = CertificateProviderRelationshipLengthOptions{
	LessThanTwoYears:           LessThanTwoYears,
	GreaterThanEqualToTwoYears: GreaterThanEqualToTwoYears,
	RelationshipLengthUnknown:  RelationshipLengthUnknown,
}

func (i CertificateProviderRelationshipLength) Empty() bool {
	return i == CertificateProviderRelationshipLength(0)
}
