// Code generated by mockery v2.46.1. DO NOT EDIT.

package donorpage

import (
	context "context"

	event "github.com/ministryofjustice/opg-modernising-lpa/internal/event"
	mock "github.com/stretchr/testify/mock"
)

// mockEventClient is an autogenerated mock type for the EventClient type
type mockEventClient struct {
	mock.Mock
}

type mockEventClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockEventClient) EXPECT() *mockEventClient_Expecter {
	return &mockEventClient_Expecter{mock: &_m.Mock}
}

// SendCertificateProviderStarted provides a mock function with given fields: ctx, e
func (_m *mockEventClient) SendCertificateProviderStarted(ctx context.Context, e event.CertificateProviderStarted) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SendCertificateProviderStarted")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.CertificateProviderStarted) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEventClient_SendCertificateProviderStarted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCertificateProviderStarted'
type mockEventClient_SendCertificateProviderStarted_Call struct {
	*mock.Call
}

// SendCertificateProviderStarted is a helper method to define mock.On call
//   - ctx context.Context
//   - e event.CertificateProviderStarted
func (_e *mockEventClient_Expecter) SendCertificateProviderStarted(ctx interface{}, e interface{}) *mockEventClient_SendCertificateProviderStarted_Call {
	return &mockEventClient_SendCertificateProviderStarted_Call{Call: _e.mock.On("SendCertificateProviderStarted", ctx, e)}
}

func (_c *mockEventClient_SendCertificateProviderStarted_Call) Run(run func(ctx context.Context, e event.CertificateProviderStarted)) *mockEventClient_SendCertificateProviderStarted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.CertificateProviderStarted))
	})
	return _c
}

func (_c *mockEventClient_SendCertificateProviderStarted_Call) Return(_a0 error) *mockEventClient_SendCertificateProviderStarted_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEventClient_SendCertificateProviderStarted_Call) RunAndReturn(run func(context.Context, event.CertificateProviderStarted) error) *mockEventClient_SendCertificateProviderStarted_Call {
	_c.Call.Return(run)
	return _c
}

// SendPaymentReceived provides a mock function with given fields: ctx, e
func (_m *mockEventClient) SendPaymentReceived(ctx context.Context, e event.PaymentReceived) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SendPaymentReceived")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.PaymentReceived) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEventClient_SendPaymentReceived_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPaymentReceived'
type mockEventClient_SendPaymentReceived_Call struct {
	*mock.Call
}

// SendPaymentReceived is a helper method to define mock.On call
//   - ctx context.Context
//   - e event.PaymentReceived
func (_e *mockEventClient_Expecter) SendPaymentReceived(ctx interface{}, e interface{}) *mockEventClient_SendPaymentReceived_Call {
	return &mockEventClient_SendPaymentReceived_Call{Call: _e.mock.On("SendPaymentReceived", ctx, e)}
}

func (_c *mockEventClient_SendPaymentReceived_Call) Run(run func(ctx context.Context, e event.PaymentReceived)) *mockEventClient_SendPaymentReceived_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.PaymentReceived))
	})
	return _c
}

func (_c *mockEventClient_SendPaymentReceived_Call) Return(_a0 error) *mockEventClient_SendPaymentReceived_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEventClient_SendPaymentReceived_Call) RunAndReturn(run func(context.Context, event.PaymentReceived) error) *mockEventClient_SendPaymentReceived_Call {
	_c.Call.Return(run)
	return _c
}

// SendReducedFeeRequested provides a mock function with given fields: ctx, e
func (_m *mockEventClient) SendReducedFeeRequested(ctx context.Context, e event.ReducedFeeRequested) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SendReducedFeeRequested")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.ReducedFeeRequested) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEventClient_SendReducedFeeRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendReducedFeeRequested'
type mockEventClient_SendReducedFeeRequested_Call struct {
	*mock.Call
}

// SendReducedFeeRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - e event.ReducedFeeRequested
func (_e *mockEventClient_Expecter) SendReducedFeeRequested(ctx interface{}, e interface{}) *mockEventClient_SendReducedFeeRequested_Call {
	return &mockEventClient_SendReducedFeeRequested_Call{Call: _e.mock.On("SendReducedFeeRequested", ctx, e)}
}

func (_c *mockEventClient_SendReducedFeeRequested_Call) Run(run func(ctx context.Context, e event.ReducedFeeRequested)) *mockEventClient_SendReducedFeeRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.ReducedFeeRequested))
	})
	return _c
}

func (_c *mockEventClient_SendReducedFeeRequested_Call) Return(_a0 error) *mockEventClient_SendReducedFeeRequested_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEventClient_SendReducedFeeRequested_Call) RunAndReturn(run func(context.Context, event.ReducedFeeRequested) error) *mockEventClient_SendReducedFeeRequested_Call {
	_c.Call.Return(run)
	return _c
}

// SendUidRequested provides a mock function with given fields: ctx, e
func (_m *mockEventClient) SendUidRequested(ctx context.Context, e event.UidRequested) error {
	ret := _m.Called(ctx, e)

	if len(ret) == 0 {
		panic("no return value specified for SendUidRequested")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.UidRequested) error); ok {
		r0 = rf(ctx, e)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockEventClient_SendUidRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUidRequested'
type mockEventClient_SendUidRequested_Call struct {
	*mock.Call
}

// SendUidRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - e event.UidRequested
func (_e *mockEventClient_Expecter) SendUidRequested(ctx interface{}, e interface{}) *mockEventClient_SendUidRequested_Call {
	return &mockEventClient_SendUidRequested_Call{Call: _e.mock.On("SendUidRequested", ctx, e)}
}

func (_c *mockEventClient_SendUidRequested_Call) Run(run func(ctx context.Context, e event.UidRequested)) *mockEventClient_SendUidRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(event.UidRequested))
	})
	return _c
}

func (_c *mockEventClient_SendUidRequested_Call) Return(_a0 error) *mockEventClient_SendUidRequested_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockEventClient_SendUidRequested_Call) RunAndReturn(run func(context.Context, event.UidRequested) error) *mockEventClient_SendUidRequested_Call {
	_c.Call.Return(run)
	return _c
}

// newMockEventClient creates a new instance of mockEventClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockEventClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockEventClient {
	mock := &mockEventClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
