// Code generated by mockery v2.45.0. DO NOT EDIT.

package donorpage

import (
	context "context"

	cron "github.com/ministryofjustice/opg-modernising-lpa/internal/cron"
	mock "github.com/stretchr/testify/mock"
)

// mockCronStore is an autogenerated mock type for the CronStore type
type mockCronStore struct {
	mock.Mock
}

type mockCronStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCronStore) EXPECT() *mockCronStore_Expecter {
	return &mockCronStore_Expecter{mock: &_m.Mock}
}

// Put provides a mock function with given fields: ctx, row
func (_m *mockCronStore) Put(ctx context.Context, row cron.Row) error {
	ret := _m.Called(ctx, row)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, cron.Row) error); ok {
		r0 = rf(ctx, row)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockCronStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type mockCronStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - row cron.Row
func (_e *mockCronStore_Expecter) Put(ctx interface{}, row interface{}) *mockCronStore_Put_Call {
	return &mockCronStore_Put_Call{Call: _e.mock.On("Put", ctx, row)}
}

func (_c *mockCronStore_Put_Call) Run(run func(ctx context.Context, row cron.Row)) *mockCronStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(cron.Row))
	})
	return _c
}

func (_c *mockCronStore_Put_Call) Return(_a0 error) *mockCronStore_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockCronStore_Put_Call) RunAndReturn(run func(context.Context, cron.Row) error) *mockCronStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCronStore creates a new instance of mockCronStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCronStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCronStore {
	mock := &mockCronStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
