// Code generated by mockery. DO NOT EDIT.

package donorpage

import (
	context "context"

	appcontext "github.com/ministryofjustice/opg-modernising-lpa/internal/appcontext"

	donordata "github.com/ministryofjustice/opg-modernising-lpa/internal/donor/donordata"

	mock "github.com/stretchr/testify/mock"

	notify "github.com/ministryofjustice/opg-modernising-lpa/internal/notify"

	sharecode "github.com/ministryofjustice/opg-modernising-lpa/internal/sharecode"
)

// mockShareCodeSender is an autogenerated mock type for the ShareCodeSender type
type mockShareCodeSender struct {
	mock.Mock
}

type mockShareCodeSender_Expecter struct {
	mock *mock.Mock
}

func (_m *mockShareCodeSender) EXPECT() *mockShareCodeSender_Expecter {
	return &mockShareCodeSender_Expecter{mock: &_m.Mock}
}

// SendCertificateProviderInvite provides a mock function with given fields: ctx, appData, invite, to
func (_m *mockShareCodeSender) SendCertificateProviderInvite(ctx context.Context, appData appcontext.Data, invite sharecode.CertificateProviderInvite, to notify.ToEmail) error {
	ret := _m.Called(ctx, appData, invite, to)

	if len(ret) == 0 {
		panic("no return value specified for SendCertificateProviderInvite")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.Data, sharecode.CertificateProviderInvite, notify.ToEmail) error); ok {
		r0 = rf(ctx, appData, invite, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockShareCodeSender_SendCertificateProviderInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCertificateProviderInvite'
type mockShareCodeSender_SendCertificateProviderInvite_Call struct {
	*mock.Call
}

// SendCertificateProviderInvite is a helper method to define mock.On call
//   - ctx context.Context
//   - appData appcontext.Data
//   - invite sharecode.CertificateProviderInvite
//   - to notify.ToEmail
func (_e *mockShareCodeSender_Expecter) SendCertificateProviderInvite(ctx interface{}, appData interface{}, invite interface{}, to interface{}) *mockShareCodeSender_SendCertificateProviderInvite_Call {
	return &mockShareCodeSender_SendCertificateProviderInvite_Call{Call: _e.mock.On("SendCertificateProviderInvite", ctx, appData, invite, to)}
}

func (_c *mockShareCodeSender_SendCertificateProviderInvite_Call) Run(run func(ctx context.Context, appData appcontext.Data, invite sharecode.CertificateProviderInvite, to notify.ToEmail)) *mockShareCodeSender_SendCertificateProviderInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(appcontext.Data), args[2].(sharecode.CertificateProviderInvite), args[3].(notify.ToEmail))
	})
	return _c
}

func (_c *mockShareCodeSender_SendCertificateProviderInvite_Call) Return(_a0 error) *mockShareCodeSender_SendCertificateProviderInvite_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockShareCodeSender_SendCertificateProviderInvite_Call) RunAndReturn(run func(context.Context, appcontext.Data, sharecode.CertificateProviderInvite, notify.ToEmail) error) *mockShareCodeSender_SendCertificateProviderInvite_Call {
	_c.Call.Return(run)
	return _c
}

// SendCertificateProviderPrompt provides a mock function with given fields: ctx, appData, provided
func (_m *mockShareCodeSender) SendCertificateProviderPrompt(ctx context.Context, appData appcontext.Data, provided *donordata.Provided) error {
	ret := _m.Called(ctx, appData, provided)

	if len(ret) == 0 {
		panic("no return value specified for SendCertificateProviderPrompt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, appcontext.Data, *donordata.Provided) error); ok {
		r0 = rf(ctx, appData, provided)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockShareCodeSender_SendCertificateProviderPrompt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendCertificateProviderPrompt'
type mockShareCodeSender_SendCertificateProviderPrompt_Call struct {
	*mock.Call
}

// SendCertificateProviderPrompt is a helper method to define mock.On call
//   - ctx context.Context
//   - appData appcontext.Data
//   - provided *donordata.Provided
func (_e *mockShareCodeSender_Expecter) SendCertificateProviderPrompt(ctx interface{}, appData interface{}, provided interface{}) *mockShareCodeSender_SendCertificateProviderPrompt_Call {
	return &mockShareCodeSender_SendCertificateProviderPrompt_Call{Call: _e.mock.On("SendCertificateProviderPrompt", ctx, appData, provided)}
}

func (_c *mockShareCodeSender_SendCertificateProviderPrompt_Call) Run(run func(ctx context.Context, appData appcontext.Data, provided *donordata.Provided)) *mockShareCodeSender_SendCertificateProviderPrompt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(appcontext.Data), args[2].(*donordata.Provided))
	})
	return _c
}

func (_c *mockShareCodeSender_SendCertificateProviderPrompt_Call) Return(_a0 error) *mockShareCodeSender_SendCertificateProviderPrompt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockShareCodeSender_SendCertificateProviderPrompt_Call) RunAndReturn(run func(context.Context, appcontext.Data, *donordata.Provided) error) *mockShareCodeSender_SendCertificateProviderPrompt_Call {
	_c.Call.Return(run)
	return _c
}

// SendVoucherAccessCode provides a mock function with given fields: ctx, donor, appData
func (_m *mockShareCodeSender) SendVoucherAccessCode(ctx context.Context, donor *donordata.Provided, appData appcontext.Data) error {
	ret := _m.Called(ctx, donor, appData)

	if len(ret) == 0 {
		panic("no return value specified for SendVoucherAccessCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *donordata.Provided, appcontext.Data) error); ok {
		r0 = rf(ctx, donor, appData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockShareCodeSender_SendVoucherAccessCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVoucherAccessCode'
type mockShareCodeSender_SendVoucherAccessCode_Call struct {
	*mock.Call
}

// SendVoucherAccessCode is a helper method to define mock.On call
//   - ctx context.Context
//   - donor *donordata.Provided
//   - appData appcontext.Data
func (_e *mockShareCodeSender_Expecter) SendVoucherAccessCode(ctx interface{}, donor interface{}, appData interface{}) *mockShareCodeSender_SendVoucherAccessCode_Call {
	return &mockShareCodeSender_SendVoucherAccessCode_Call{Call: _e.mock.On("SendVoucherAccessCode", ctx, donor, appData)}
}

func (_c *mockShareCodeSender_SendVoucherAccessCode_Call) Run(run func(ctx context.Context, donor *donordata.Provided, appData appcontext.Data)) *mockShareCodeSender_SendVoucherAccessCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*donordata.Provided), args[2].(appcontext.Data))
	})
	return _c
}

func (_c *mockShareCodeSender_SendVoucherAccessCode_Call) Return(_a0 error) *mockShareCodeSender_SendVoucherAccessCode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockShareCodeSender_SendVoucherAccessCode_Call) RunAndReturn(run func(context.Context, *donordata.Provided, appcontext.Data) error) *mockShareCodeSender_SendVoucherAccessCode_Call {
	_c.Call.Return(run)
	return _c
}

// newMockShareCodeSender creates a new instance of mockShareCodeSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockShareCodeSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockShareCodeSender {
	mock := &mockShareCodeSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
