// Code generated by mockery v2.20.0. DO NOT EDIT.

package donor

import (
	context "context"

	notify "github.com/ministryofjustice/opg-modernising-lpa/app/internal/notify"
	mock "github.com/stretchr/testify/mock"

	page "github.com/ministryofjustice/opg-modernising-lpa/app/internal/page"
)

// mockSMSSender is an autogenerated mock type for the SMSSender type
type mockSMSSender struct {
	mock.Mock
}

// PaperCertificateProviderMeetingPrompt provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *mockSMSSender) PaperCertificateProviderMeetingPrompt(_a0 context.Context, _a1 *page.Lpa, _a2 page.AppData, _a3 notify.TemplateId) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *page.Lpa, page.AppData, notify.TemplateId) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockSMSSender interface {
	mock.TestingT
	Cleanup(func())
}

// newMockSMSSender creates a new instance of mockSMSSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockSMSSender(t mockConstructorTestingTnewMockSMSSender) *mockSMSSender {
	mock := &mockSMSSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
