// Code generated by mockery v2.39.1. DO NOT EDIT.

package app

import (
	context "context"

	types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	mock "github.com/stretchr/testify/mock"
)

// mockDynamoUpdateClient is an autogenerated mock type for the DynamoUpdateClient type
type mockDynamoUpdateClient struct {
	mock.Mock
}

type mockDynamoUpdateClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDynamoUpdateClient) EXPECT() *mockDynamoUpdateClient_Expecter {
	return &mockDynamoUpdateClient_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: ctx, pk, sk, values, expression
func (_m *mockDynamoUpdateClient) Update(ctx context.Context, pk string, sk string, values map[string]types.AttributeValue, expression string) error {
	ret := _m.Called(ctx, pk, sk, values, expression)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]types.AttributeValue, string) error); ok {
		r0 = rf(ctx, pk, sk, values, expression)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamoUpdateClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockDynamoUpdateClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - sk string
//   - values map[string]types.AttributeValue
//   - expression string
func (_e *mockDynamoUpdateClient_Expecter) Update(ctx interface{}, pk interface{}, sk interface{}, values interface{}, expression interface{}) *mockDynamoUpdateClient_Update_Call {
	return &mockDynamoUpdateClient_Update_Call{Call: _e.mock.On("Update", ctx, pk, sk, values, expression)}
}

func (_c *mockDynamoUpdateClient_Update_Call) Run(run func(ctx context.Context, pk string, sk string, values map[string]types.AttributeValue, expression string)) *mockDynamoUpdateClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]types.AttributeValue), args[4].(string))
	})
	return _c
}

func (_c *mockDynamoUpdateClient_Update_Call) Return(_a0 error) *mockDynamoUpdateClient_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamoUpdateClient_Update_Call) RunAndReturn(run func(context.Context, string, string, map[string]types.AttributeValue, string) error) *mockDynamoUpdateClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDynamoUpdateClient creates a new instance of mockDynamoUpdateClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDynamoUpdateClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDynamoUpdateClient {
	mock := &mockDynamoUpdateClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
