// Code generated by mockery v2.45.0. DO NOT EDIT.

package app

import (
	http "net/http"

	sesh "github.com/ministryofjustice/opg-modernising-lpa/internal/sesh"
	mock "github.com/stretchr/testify/mock"
)

// mockSessionStore is an autogenerated mock type for the SessionStore type
type mockSessionStore struct {
	mock.Mock
}

type mockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockSessionStore) EXPECT() *mockSessionStore_Expecter {
	return &mockSessionStore_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: r
func (_m *mockSessionStore) Login(r *http.Request) (*sesh.LoginSession, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *sesh.LoginSession
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*sesh.LoginSession, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *sesh.LoginSession); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sesh.LoginSession)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockSessionStore_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type mockSessionStore_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - r *http.Request
func (_e *mockSessionStore_Expecter) Login(r interface{}) *mockSessionStore_Login_Call {
	return &mockSessionStore_Login_Call{Call: _e.mock.On("Login", r)}
}

func (_c *mockSessionStore_Login_Call) Run(run func(r *http.Request)) *mockSessionStore_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *mockSessionStore_Login_Call) Return(_a0 *sesh.LoginSession, _a1 error) *mockSessionStore_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockSessionStore_Login_Call) RunAndReturn(run func(*http.Request) (*sesh.LoginSession, error)) *mockSessionStore_Login_Call {
	_c.Call.Return(run)
	return _c
}

// newMockSessionStore creates a new instance of mockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockSessionStore {
	mock := &mockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
