deployments:
  environmentMapping:
    development:
      - "dev_*"
      - "weblate"
    testing:
      - "demo"
      - "ur"
      - "test"
    staging:
      - "preproduction"
    production:
      - "production"
