// Code generated by mockery v2.20.0. DO NOT EDIT.

package certificateprovider

import (
	context "context"

	actor "github.com/ministryofjustice/opg-modernising-lpa/internal/actor"

	mock "github.com/stretchr/testify/mock"
)

// mockLpaStoreClient is an autogenerated mock type for the LpaStoreClient type
type mockLpaStoreClient struct {
	mock.Mock
}

// SendCertificateProvider provides a mock function with given fields: _a0, _a1, _a2
func (_m *mockLpaStoreClient) SendCertificateProvider(_a0 context.Context, _a1 string, _a2 *actor.CertificateProviderProvidedDetails) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *actor.CertificateProviderProvidedDetails) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockLpaStoreClient interface {
	mock.TestingT
	Cleanup(func())
}

// newMockLpaStoreClient creates a new instance of mockLpaStoreClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockLpaStoreClient(t mockConstructorTestingTnewMockLpaStoreClient) *mockLpaStoreClient {
	mock := &mockLpaStoreClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
