// Code generated by "enumerator -type ReplacementAttorneysStepIn -linecomment -trimprefix -empty"; DO NOT EDIT.
package page

import (
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ReplacementAttorneysStepInWhenAllCanNoLongerAct-1]
	_ = x[ReplacementAttorneysStepInWhenOneCanNoLongerAct-2]
	_ = x[ReplacementAttorneysStepInAnotherWay-3]
}

const _ReplacementAttorneysStepIn_name = "alloneother"

var _ReplacementAttorneysStepIn_index = [...]uint8{0, 3, 6, 11}

func (i ReplacementAttorneysStepIn) String() string {
	i -= 1
	if i >= ReplacementAttorneysStepIn(len(_ReplacementAttorneysStepIn_index)-1) {
		return "ReplacementAttorneysStepIn(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ReplacementAttorneysStepIn_name[_ReplacementAttorneysStepIn_index[i]:_ReplacementAttorneysStepIn_index[i+1]]
}

func (i ReplacementAttorneysStepIn) IsWhenAllCanNoLongerAct() bool {
	return i == ReplacementAttorneysStepInWhenAllCanNoLongerAct
}

func (i ReplacementAttorneysStepIn) IsWhenOneCanNoLongerAct() bool {
	return i == ReplacementAttorneysStepInWhenOneCanNoLongerAct
}

func (i ReplacementAttorneysStepIn) IsAnotherWay() bool {
	return i == ReplacementAttorneysStepInAnotherWay
}

func ParseReplacementAttorneysStepIn(s string) (ReplacementAttorneysStepIn, error) {
	switch s {
	case "all":
		return ReplacementAttorneysStepInWhenAllCanNoLongerAct, nil
	case "one":
		return ReplacementAttorneysStepInWhenOneCanNoLongerAct, nil
	case "other":
		return ReplacementAttorneysStepInAnotherWay, nil
	default:
		return ReplacementAttorneysStepIn(0), fmt.Errorf("invalid ReplacementAttorneysStepIn '%s'", s)
	}
}

type ReplacementAttorneysStepInOptions struct {
	WhenAllCanNoLongerAct ReplacementAttorneysStepIn
	WhenOneCanNoLongerAct ReplacementAttorneysStepIn
	AnotherWay            ReplacementAttorneysStepIn
}

var ReplacementAttorneysStepInValues = ReplacementAttorneysStepInOptions{
	WhenAllCanNoLongerAct: ReplacementAttorneysStepInWhenAllCanNoLongerAct,
	WhenOneCanNoLongerAct: ReplacementAttorneysStepInWhenOneCanNoLongerAct,
	AnotherWay:            ReplacementAttorneysStepInAnotherWay,
}

func (i ReplacementAttorneysStepIn) Empty() bool {
	return i == ReplacementAttorneysStepIn(0)
}
