// Code generated by mockery v2.39.1. DO NOT EDIT.

package page

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// mockLogger is an autogenerated mock type for the Logger type
type mockLogger struct {
	mock.Mock
}

// Print provides a mock function with given fields: v
func (_m *mockLogger) Print(v ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, v...)
	_m.Called(_ca...)
}

// Request provides a mock function with given fields: _a0, _a1
func (_m *mockLogger) Request(_a0 *http.Request, _a1 error) {
	_m.Called(_a0, _a1)
}

// newMockLogger creates a new instance of mockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockLogger {
	mock := &mockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
