// Code generated by mockery v2.20.0. DO NOT EDIT.

package page

import (
	localize "github.com/ministryofjustice/opg-modernising-lpa/internal/localize"
	mock "github.com/stretchr/testify/mock"
)

// mockBundle is an autogenerated mock type for the Bundle type
type mockBundle struct {
	mock.Mock
}

// For provides a mock function with given fields: lang
func (_m *mockBundle) For(lang localize.Lang) *localize.Localizer {
	ret := _m.Called(lang)

	var r0 *localize.Localizer
	if rf, ok := ret.Get(0).(func(localize.Lang) *localize.Localizer); ok {
		r0 = rf(lang)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*localize.Localizer)
		}
	}

	return r0
}

type mockConstructorTestingTnewMockBundle interface {
	mock.TestingT
	Cleanup(func())
}

// newMockBundle creates a new instance of mockBundle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockBundle(t mockConstructorTestingTnewMockBundle) *mockBundle {
	mock := &mockBundle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
