// Code generated by mockery v2.20.0. DO NOT EDIT.

package page

import (
	context "context"

	"github.com/ministryofjustice/opg-modernising-lpa/internal/donor/donordata"
	mock "github.com/stretchr/testify/mock"
)

// mockShareCodeSender is an autogenerated mock type for the shareCodeSender type
type mockShareCodeSender struct {
	mock.Mock
}

// SendAttorneys provides a mock function with given fields: ctx, appData, donor
func (_m *mockShareCodeSender) SendAttorneys(ctx context.Context, appData AppData, donor *donordata.Provided) error {
	ret := _m.Called(ctx, appData, donor)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, AppData, *donordata.Provided) error); ok {
		r0 = rf(ctx, appData, donor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendCertificateProvider provides a mock function with given fields: ctx, appData, identity, donor
func (_m *mockShareCodeSender) SendCertificateProvider(ctx context.Context, appData AppData, identity bool, donor *donordata.Provided) error {
	ret := _m.Called(ctx, appData, identity, donor)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, AppData, bool, *donordata.Provided) error); ok {
		r0 = rf(ctx, appData, identity, donor)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockShareCodeSender interface {
	mock.TestingT
	Cleanup(func())
}

// newMockShareCodeSender creates a new instance of mockShareCodeSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockShareCodeSender(t mockConstructorTestingTnewMockShareCodeSender) *mockShareCodeSender {
	mock := &mockShareCodeSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
