graph TB
  linkStyle default fill:#ffffff

  subgraph diagram [Make a Lasting Power of Attorney Online - Containers]
    style diagram fill:#ffffff,stroke:#ffffff

    11("<div style='font-weight: bold'>GOV.UK Pay</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles Payments for Donors.</div>")
    style 11 fill:#999999,stroke:#6b6b6b,color:#ffffff
    1["<div style='font-weight: bold'>Attorney</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Attorney interacting with a<br />Lasting Power of Attorney.</div>"]
    style 1 fill:#08427b,stroke:#052e56,color:#ffffff
    12("<div style='font-weight: bold'>GOV.UK One Login</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles Authentication and<br />Identification of Actors.</div>")
    style 12 fill:#999999,stroke:#6b6b6b,color:#ffffff
    2["<div style='font-weight: bold'>Donor</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Donor drafting the Lasting<br />Power of Attorney.</div>"]
    style 2 fill:#08427b,stroke:#052e56,color:#ffffff
    13("<div style='font-weight: bold'>Yoti</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Used for identity.</div>")
    style 13 fill:#999999,stroke:#6b6b6b,color:#ffffff
    3["<div style='font-weight: bold'>Certificate Provider</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Certificate Provider<br />interacting with a Lasting<br />Power of Attorney.</div>"]
    style 3 fill:#08427b,stroke:#052e56,color:#ffffff
    14("<div style='font-weight: bold'>Ordanance survey</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Used for identity.</div>")
    style 14 fill:#999999,stroke:#6b6b6b,color:#ffffff
    10("<div style='font-weight: bold'>GOV.UK Notify</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles SMS, Email and<br />Letters.</div>")
    style 10 fill:#999999,stroke:#6b6b6b,color:#ffffff

    subgraph 4 [Make a Lasting Power of Attorney Online]
      style 4 fill:#ffffff,stroke:#444444,color:#444444

      5["<div style='font-weight: bold'>App</div><div style='font-size: 70%; margin-top: 0px'>[Container: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Provides and delivers static<br />content, business logic,<br />routing, third party access<br />and database access</div>"]
      style 5 fill:#438dd5,stroke:#2e6295,color:#ffffff
      6[("<div style='font-weight: bold'>Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: DynamoDB]</div><div style='font-size: 80%; margin-top:10px'>Stores actor information,<br />Draft LPA details, access<br />logs, etc.</div>")]
      style 6 fill:#438dd5,stroke:#2e6295,color:#ffffff
      7[("<div style='font-weight: bold'>Monitoring and Telemetery</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS Cloudwatch]</div><div style='font-size: 80%; margin-top:10px'>Cloudwatch logs, X-Ray and<br />RUM</div>")]
      style 7 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

    3-. "<div>Uses</div><div style='font-size: 70%'></div>" .->5
    2-. "<div>Uses</div><div style='font-size: 70%'></div>" .->5
    1-. "<div>Uses</div><div style='font-size: 70%'></div>" .->5
    5-. "<div>Reads from and writes to</div><div style='font-size: 70%'></div>" .->6
    5-. "<div>Writes to</div><div style='font-size: 70%'></div>" .->7
    5-. "<div>Sends communication with</div><div style='font-size: 70%'></div>" .->10
    5-. "<div>Handles payment with</div><div style='font-size: 70%'></div>" .->11
    5-. "<div>Authenticates users with</div><div style='font-size: 70%'></div>" .->12
    5-. "<div>Identifies users with</div><div style='font-size: 70%'></div>" .->13
    5-. "<div>Looks up addressed with</div><div style='font-size: 70%'></div>" .->14
  end