graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Make and Register a Lasting Power of Attorney Online - Containers"]
    style diagram fill:#ffffff,stroke:#ffffff

    2["<div style='font-weight: bold'>Attorney</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Attorney interacting with a<br />Lasting Power of Attorney.</div>"]
    style 2 fill:#08427b,stroke:#052e56,color:#ffffff
    3["<div style='font-weight: bold'>Donor</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Donor drafting the Lasting<br />Power of Attorney.</div>"]
    style 3 fill:#08427b,stroke:#052e56,color:#ffffff
    4["<div style='font-weight: bold'>Certificate Provider</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Certificate Provider<br />interacting with a Lasting<br />Power of Attorney.</div>"]
    style 4 fill:#08427b,stroke:#052e56,color:#ffffff
    6["<div style='font-weight: bold'>Organisation</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div><div style='font-size: 80%; margin-top:10px'>Organisation or charity.</div>"]
    style 6 fill:#08427b,stroke:#052e56,color:#ffffff
    21("<div style='font-weight: bold'>GOV.UK Notify</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles SMS, Email and<br />Letters.</div>")
    style 21 fill:#999999,stroke:#6b6b6b,color:#ffffff
    22("<div style='font-weight: bold'>GOV.UK Pay</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles Payments for Donors.</div>")
    style 22 fill:#999999,stroke:#6b6b6b,color:#ffffff
    23("<div style='font-weight: bold'>GOV.UK One Login</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles Authentication and<br />Identification of Actors.</div>")
    style 23 fill:#999999,stroke:#6b6b6b,color:#ffffff
    24("<div style='font-weight: bold'>Ordanance survey</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Used for postcode lookup.</div>")
    style 24 fill:#999999,stroke:#6b6b6b,color:#ffffff
    25("<div style='font-weight: bold'>Sirius Case Management</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Handles OPG casework tasks.</div>")
    style 25 fill:#1168bd,stroke:#0b4884,color:#ffffff
    26("<div style='font-weight: bold'>LPA Store</div><div style='font-size: 70%; margin-top: 0px'>[Software System]</div><div style='font-size: 80%; margin-top:10px'>Stores completed LPA.</div>")
    style 26 fill:#1168bd,stroke:#0b4884,color:#ffffff

    subgraph 7 [Make and Register a Lasting Power of Attorney Online]
      style 7 fill:#ffffff,stroke:#0b4884,color:#0b4884

      10["<div style='font-weight: bold'>App</div><div style='font-size: 70%; margin-top: 0px'>[Container: Go, HTML, CSS, JS]</div><div style='font-size: 80%; margin-top:10px'>Provides and delivers static<br />content, business logic,<br />routing, third party access<br />and database access</div>"]
      style 10 fill:#438dd5,stroke:#2e6295,color:#ffffff
      8[("<div style='font-weight: bold'>Database</div><div style='font-size: 70%; margin-top: 0px'>[Container: DynamoDB]</div><div style='font-size: 80%; margin-top:10px'>Stores actor information,<br />Draft LPA details etc.</div>")]
      style 8 fill:#438dd5,stroke:#2e6295,color:#ffffff
      9[("<div style='font-weight: bold'>Monitoring and Telemetery</div><div style='font-size: 70%; margin-top: 0px'>[Container: AWS Cloudwatch]</div><div style='font-size: 80%; margin-top:10px'>Cloudwatch logs, X-Ray and<br />RUM</div>")]
      style 9 fill:#438dd5,stroke:#2e6295,color:#ffffff
    end

    10-. "<div>Reads from and writes to</div><div style='font-size: 70%'></div>" .->8
    10-. "<div>Writes to</div><div style='font-size: 70%'></div>" .->9
    4-. "<div>Uses</div><div style='font-size: 70%'></div>" .->10
    3-. "<div>Uses</div><div style='font-size: 70%'></div>" .->10
    2-. "<div>Uses</div><div style='font-size: 70%'></div>" .->10
    6-. "<div>Uses</div><div style='font-size: 70%'></div>" .->10
    10-. "<div>Sends communication with</div><div style='font-size: 70%'></div>" .->21
    10-. "<div>Handles payment with</div><div style='font-size: 70%'></div>" .->22
    10-. "<div>Authenticates users with</div><div style='font-size: 70%'></div>" .->23
    10-. "<div>Looks up addressed with</div><div style='font-size: 70%'></div>" .->24
    10-. "<div>Sends events and documents to</div><div style='font-size: 70%'></div>" .->25
    10-. "<div>Sends completed LPA to</div><div style='font-size: 70%'></div>" .->26
  end