plugin: openapi
specFile: https://raw.githubusercontent.com/alphagov/pay-publicapi/master/openapi/publicapi_spec.json
#response:
#  scriptFile: payments.js

#resources:
#  - path: "/v1/payments/:paymentId"
#    method: GET
#    contentType: application/json
#    response:
#      scriptFile: payments.js
#
#  - path: "/v1/payments"
#    method: POST
#    contentType: application/json
#    response:
#      scriptFile: payments.js
#    capture:
#      amount:
#        jsonPath: $.Amount
#        store: paymentStore

validation:
  request: true
