// Code generated by mockery v2.20.0. DO NOT EDIT.

package attorney

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDataStore is an autogenerated mock type for the DataStore type
type mockDataStore struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, pk, sk, v
func (_m *mockDataStore) Get(ctx context.Context, pk string, sk string, v interface{}) error {
	ret := _m.Called(ctx, pk, sk, v)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, pk, sk, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockDataStore interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDataStore creates a new instance of mockDataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDataStore(t mockConstructorTestingTnewMockDataStore) *mockDataStore {
	mock := &mockDataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
