// Code generated by "enumerator -type CorrespondentShare -linecomment -trimprefix -empty -bits"; DO NOT EDIT.
package donordata

import (
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CorrespondentShareAttorneys-2]
	_ = x[CorrespondentShareCertificateProvider-4]
}

const (
	_CorrespondentShare_name_0 = "Attorneys"
	_CorrespondentShare_name_1 = "CertificateProvider"
)

func (i CorrespondentShare) String() string {
	switch {
	case i == 2:
		return _CorrespondentShare_name_0
	case i == 4:
		return _CorrespondentShare_name_1
	default:
		return "CorrespondentShare(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

func (i CorrespondentShare) Strings() []string {
	var result []string
	if i.HasAttorneys() {
		result = append(result, CorrespondentShareAttorneys.String())
	}
	if i.HasCertificateProvider() {
		result = append(result, CorrespondentShareCertificateProvider.String())
	}
	return result
}

func (i CorrespondentShare) HasAttorneys() bool {
	return i&CorrespondentShareAttorneys != 0
}

func (i CorrespondentShare) HasCertificateProvider() bool {
	return i&CorrespondentShareCertificateProvider != 0
}

func ParseCorrespondentShare(strs []string) (CorrespondentShare, error) {
	var result CorrespondentShare

	for _, s := range strs {
		switch s {
		case "Attorneys":
			result |= CorrespondentShareAttorneys
		case "CertificateProvider":
			result |= CorrespondentShareCertificateProvider
		default:
			return CorrespondentShare(0), fmt.Errorf("invalid CorrespondentShare '%s'", s)
		}
	}

	return result, nil
}

type CorrespondentShareOptions struct {
	Attorneys           CorrespondentShare
	CertificateProvider CorrespondentShare
}

var CorrespondentShareValues = CorrespondentShareOptions{
	Attorneys:           CorrespondentShareAttorneys,
	CertificateProvider: CorrespondentShareCertificateProvider,
}

func (i CorrespondentShare) Empty() bool {
	return i == CorrespondentShare(0)
}
