package page

const (
	AuthPath         = "/auth"
	AuthRedirectPath = "/auth/redirect"

	aboutPaymentPath                                = "/about-payment"
	certificateProviderDetailsPath                  = "/certificate-provider-details"
	checkYourLpaPath                                = "/check-your-lpa"
	chooseAttorneysAddressPath                      = "/choose-attorneys-address"
	chooseAttorneysPath                             = "/choose-attorneys"
	dashboardPath                                   = "/dashboard"
	howDoYouKnowYourCertificateProviderPath         = "/how-do-you-know-your-certificate-provider"
	howLongHaveYouKnownCertificateProviderPath      = "/how-long-have-you-known-certificate-provider"
	howToSignPath                                   = "/how-to-sign"
	howWouldYouLikeToBeContactedPath                = "/how-would-you-like-to-be-contacted"
	identityConfirmedPath                           = "/identity-confirmed"
	identityWithCouncilTaxBillPath                  = "/id/council-tax-bill"
	identityWithDrivingLicencePath                  = "/id/driving-licence"
	identityWithDwpAccountPath                      = "/id/dwp-account"
	identityWithGovernmentGatewayAccountPath        = "/id/government-gateway-account"
	identityWithOnlineBankAccountPath               = "/id/online-bank-account"
	identityWithPassportPath                        = "/id/passport"
	identityWithUtilityBillPath                     = "/id/utility-bill"
	identityWithYotiCallbackPath                    = "/id/yoti/callback"
	identityWithYotiPath                            = "/id/yoti"
	lpaTypePath                                     = "/lpa-type"
	paymentConfirmationPath                         = "/payment-confirmation"
	readYourLpaPath                                 = "/read-your-lpa"
	restrictionsPath                                = "/restrictions"
	selectYourIdentityOptionsPath                   = "/select-your-identity-options"
	signingConfirmationPath                         = "/signing-confirmation"
	startPath                                       = "/start"
	taskListPath                                    = "/task-list"
	wantReplacementAttorneysPath                    = "/want-replacement-attorneys"
	whatHappensNextPath                             = "/what-happens-next"
	whatHappensWhenSigningPath                      = "/what-happens-when-signing"
	whenCanTheLpaBeUsedPath                         = "/when-can-the-lpa-be-used"
	whoDoYouWantToBeCertificateProviderGuidancePath = "/who-do-you-want-to-be-certificate-provider-guidance"
	whoIsTheLpaForPath                              = "/who-is-the-lpa-for"
	yourAddressPath                                 = "/your-address"
	yourChosenIdentityOptionsPath                   = "/your-chosen-identity-options"
	yourDetailsPath                                 = "/your-details"
)
