package page

type AppPaths struct {
	AboutPayment                                string
	Auth                                        string
	AuthRedirect                                string
	CertificateProviderDetails                  string
	CheckYourLpa                                string
	ChooseAttorneys                             string
	ChooseAttorneysAddress                      string
	ChooseAttorneysSummary                      string
	ChoosePeopleToNotify                        string
	ChoosePeopleToNotifyAddress                 string
	ChoosePeopleToNotifySummary                 string
	ChooseReplacementAttorneys                  string
	ChooseReplacementAttorneysAddress           string
	ChooseReplacementAttorneysSummary           string
	CookiesConsent                              string
	Dashboard                                   string
	DoYouWantReplacementAttorneys               string
	DoYouWantToNotifyPeople                     string
	HealthCheck                                 string
	HowDoYouKnowYourCertificateProvider         string
	HowLongHaveYouKnownCertificateProvider      string
	HowShouldAttorneysMakeDecisions             string
	HowShouldReplacementAttorneysMakeDecisions  string
	HowShouldReplacementAttorneysStepIn         string
	HowToSign                                   string
	HowWouldYouLikeToBeContacted                string
	IdentityConfirmed                           string
	IdentityWithBiometricResidencePermit        string
	IdentityWithDrivingLicencePaper             string
	IdentityWithDrivingLicencePhotocard         string
	IdentityWithOneLogin                        string
	IdentityWithOnlineBankAccount               string
	IdentityWithPassport                        string
	IdentityWithYoti                            string
	IdentityWithYotiCallback                    string
	LpaType                                     string
	PaymentConfirmation                         string
	ReadYourLpa                                 string
	RemoveAttorney                              string
	RemovePersonToNotify                        string
	RemoveReplacementAttorney                   string
	Restrictions                                string
	Root                                        string
	SelectYourIdentityOptions                   string
	SelectYourIdentityOptions1                  string
	SelectYourIdentityOptions2                  string
	SignYourLpa                                 string
	SigningConfirmation                         string
	Start                                       string
	TaskList                                    string
	TestingStart                                string
	WhatHappensWhenSigning                      string
	WhenCanTheLpaBeUsed                         string
	WhoDoYouWantToBeCertificateProviderGuidance string
	WhoIsTheLpaFor                              string
	WitnessingYourSignature                     string
	YourAddress                                 string
	YourChosenIdentityOptions                   string
	YourDetails                                 string
}
