package page

const (
	AuthPath         = "/auth"
	AuthRedirectPath = "/auth/redirect"

	aboutPaymentPath                                = "/about-payment"
	certificateProviderDetailsPath                  = "/certificate-provider-details"
	checkYourLpaPath                                = "/check-your-lpa"
	chooseAttorneysAddressPath                      = "/choose-attorneys-address"
	chooseAttorneysPath                             = "/choose-attorneys"
	howDoYouKnowYourCertificateProviderPath         = "/how-do-you-know-your-certificate-provider"
	howLongHaveYouKnownCertificateProviderPath      = "/how-long-have-you-known-certificate-provider"
	howToSignPath                                   = "/how-to-sign"
	howWouldYouLikeToBeContactedPath                = "/how-would-you-like-to-be-contacted"
	lpaTypePath                                     = "/lpa-type"
	readYourLpaPath                                 = "/read-your-lpa"
	paymentConfirmationPath                         = "/payment-confirmation"
	restrictionsPath                                = "/restrictions"
	selectYourIdentityOptionsPath                   = "/select-your-identity-options"
	startPath                                       = "/start"
	taskListPath                                    = "/task-list"
	wantReplacementAttorneysPath                    = "/want-replacement-attorneys"
	whatHappensNextPath                             = "/what-happens-next"
	whatHappensWhenSigningPath                      = "/what-happens-when-signing"
	whenCanTheLpaBeUsedPath                         = "/when-can-the-lpa-be-used"
	whoDoYouWantToBeCertificateProviderGuidancePath = "/who-do-you-want-to-be-certificate-provider-guidance"
	whoIsTheLpaForPath                              = "/who-is-the-lpa-for"
	yourAddressPath                                 = "/your-address"
	yourDetailsPath                                 = "/your-details"
)
