// Code generated by mockery v2.39.1. DO NOT EDIT.

package supporter

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockOrganisationStore is an autogenerated mock type for the OrganisationStore type
type mockOrganisationStore struct {
	mock.Mock
}

type mockOrganisationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOrganisationStore) EXPECT() *mockOrganisationStore_Expecter {
	return &mockOrganisationStore_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: _a0, _a1
func (_m *mockOrganisationStore) Create(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOrganisationStore_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockOrganisationStore_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *mockOrganisationStore_Expecter) Create(_a0 interface{}, _a1 interface{}) *mockOrganisationStore_Create_Call {
	return &mockOrganisationStore_Create_Call{Call: _e.mock.On("Create", _a0, _a1)}
}

func (_c *mockOrganisationStore_Create_Call) Run(run func(_a0 context.Context, _a1 string)) *mockOrganisationStore_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockOrganisationStore_Create_Call) Return(_a0 error) *mockOrganisationStore_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrganisationStore_Create_Call) RunAndReturn(run func(context.Context, string) error) *mockOrganisationStore_Create_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOrganisationStore creates a new instance of mockOrganisationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOrganisationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOrganisationStore {
	mock := &mockOrganisationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
