// Code generated by mockery. DO NOT EDIT.

package scheduled

import (
	context "context"

	localize "github.com/ministryofjustice/opg-modernising-lpa/internal/localize"
	mock "github.com/stretchr/testify/mock"

	notify "github.com/ministryofjustice/opg-modernising-lpa/internal/notify"
)

// mockNotifyClient is an autogenerated mock type for the NotifyClient type
type mockNotifyClient struct {
	mock.Mock
}

type mockNotifyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockNotifyClient) EXPECT() *mockNotifyClient_Expecter {
	return &mockNotifyClient_Expecter{mock: &_m.Mock}
}

// SendActorEmail provides a mock function with given fields: ctx, lang, to, lpaUID, email
func (_m *mockNotifyClient) SendActorEmail(ctx context.Context, lang localize.Lang, to string, lpaUID string, email notify.Email) error {
	ret := _m.Called(ctx, lang, to, lpaUID, email)

	if len(ret) == 0 {
		panic("no return value specified for SendActorEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, localize.Lang, string, string, notify.Email) error); ok {
		r0 = rf(ctx, lang, to, lpaUID, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockNotifyClient_SendActorEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendActorEmail'
type mockNotifyClient_SendActorEmail_Call struct {
	*mock.Call
}

// SendActorEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - lang localize.Lang
//   - to string
//   - lpaUID string
//   - email notify.Email
func (_e *mockNotifyClient_Expecter) SendActorEmail(ctx interface{}, lang interface{}, to interface{}, lpaUID interface{}, email interface{}) *mockNotifyClient_SendActorEmail_Call {
	return &mockNotifyClient_SendActorEmail_Call{Call: _e.mock.On("SendActorEmail", ctx, lang, to, lpaUID, email)}
}

func (_c *mockNotifyClient_SendActorEmail_Call) Run(run func(ctx context.Context, lang localize.Lang, to string, lpaUID string, email notify.Email)) *mockNotifyClient_SendActorEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(localize.Lang), args[2].(string), args[3].(string), args[4].(notify.Email))
	})
	return _c
}

func (_c *mockNotifyClient_SendActorEmail_Call) Return(_a0 error) *mockNotifyClient_SendActorEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockNotifyClient_SendActorEmail_Call) RunAndReturn(run func(context.Context, localize.Lang, string, string, notify.Email) error) *mockNotifyClient_SendActorEmail_Call {
	_c.Call.Return(run)
	return _c
}

// newMockNotifyClient creates a new instance of mockNotifyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockNotifyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockNotifyClient {
	mock := &mockNotifyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
