// Code generated by mockery. DO NOT EDIT.

package scheduled

import (
	context "context"

	dynamo "github.com/ministryofjustice/opg-modernising-lpa/internal/dynamo"
	mock "github.com/stretchr/testify/mock"
)

// mockDynamoClient is an autogenerated mock type for the DynamoClient type
type mockDynamoClient struct {
	mock.Mock
}

type mockDynamoClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDynamoClient) EXPECT() *mockDynamoClient_Expecter {
	return &mockDynamoClient_Expecter{mock: &_m.Mock}
}

// AllByLpaUIDAndPartialSK provides a mock function with given fields: ctx, uid, partialSK, v
func (_m *mockDynamoClient) AllByLpaUIDAndPartialSK(ctx context.Context, uid string, partialSK string, v interface{}) error {
	ret := _m.Called(ctx, uid, partialSK, v)

	if len(ret) == 0 {
		panic("no return value specified for AllByLpaUIDAndPartialSK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, uid, partialSK, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamoClient_AllByLpaUIDAndPartialSK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllByLpaUIDAndPartialSK'
type mockDynamoClient_AllByLpaUIDAndPartialSK_Call struct {
	*mock.Call
}

// AllByLpaUIDAndPartialSK is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - partialSK string
//   - v interface{}
func (_e *mockDynamoClient_Expecter) AllByLpaUIDAndPartialSK(ctx interface{}, uid interface{}, partialSK interface{}, v interface{}) *mockDynamoClient_AllByLpaUIDAndPartialSK_Call {
	return &mockDynamoClient_AllByLpaUIDAndPartialSK_Call{Call: _e.mock.On("AllByLpaUIDAndPartialSK", ctx, uid, partialSK, v)}
}

func (_c *mockDynamoClient_AllByLpaUIDAndPartialSK_Call) Run(run func(ctx context.Context, uid string, partialSK string, v interface{})) *mockDynamoClient_AllByLpaUIDAndPartialSK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *mockDynamoClient_AllByLpaUIDAndPartialSK_Call) Return(_a0 error) *mockDynamoClient_AllByLpaUIDAndPartialSK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamoClient_AllByLpaUIDAndPartialSK_Call) RunAndReturn(run func(context.Context, string, string, interface{}) error) *mockDynamoClient_AllByLpaUIDAndPartialSK_Call {
	_c.Call.Return(run)
	return _c
}

// AnyByPK provides a mock function with given fields: ctx, pk, v
func (_m *mockDynamoClient) AnyByPK(ctx context.Context, pk dynamo.PK, v interface{}) error {
	ret := _m.Called(ctx, pk, v)

	if len(ret) == 0 {
		panic("no return value specified for AnyByPK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dynamo.PK, interface{}) error); ok {
		r0 = rf(ctx, pk, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamoClient_AnyByPK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnyByPK'
type mockDynamoClient_AnyByPK_Call struct {
	*mock.Call
}

// AnyByPK is a helper method to define mock.On call
//   - ctx context.Context
//   - pk dynamo.PK
//   - v interface{}
func (_e *mockDynamoClient_Expecter) AnyByPK(ctx interface{}, pk interface{}, v interface{}) *mockDynamoClient_AnyByPK_Call {
	return &mockDynamoClient_AnyByPK_Call{Call: _e.mock.On("AnyByPK", ctx, pk, v)}
}

func (_c *mockDynamoClient_AnyByPK_Call) Run(run func(ctx context.Context, pk dynamo.PK, v interface{})) *mockDynamoClient_AnyByPK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dynamo.PK), args[2].(interface{}))
	})
	return _c
}

func (_c *mockDynamoClient_AnyByPK_Call) Return(_a0 error) *mockDynamoClient_AnyByPK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamoClient_AnyByPK_Call) RunAndReturn(run func(context.Context, dynamo.PK, interface{}) error) *mockDynamoClient_AnyByPK_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteManyByUID provides a mock function with given fields: ctx, keys, uid
func (_m *mockDynamoClient) DeleteManyByUID(ctx context.Context, keys []dynamo.Keys, uid string) error {
	ret := _m.Called(ctx, keys, uid)

	if len(ret) == 0 {
		panic("no return value specified for DeleteManyByUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dynamo.Keys, string) error); ok {
		r0 = rf(ctx, keys, uid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamoClient_DeleteManyByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteManyByUID'
type mockDynamoClient_DeleteManyByUID_Call struct {
	*mock.Call
}

// DeleteManyByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []dynamo.Keys
//   - uid string
func (_e *mockDynamoClient_Expecter) DeleteManyByUID(ctx interface{}, keys interface{}, uid interface{}) *mockDynamoClient_DeleteManyByUID_Call {
	return &mockDynamoClient_DeleteManyByUID_Call{Call: _e.mock.On("DeleteManyByUID", ctx, keys, uid)}
}

func (_c *mockDynamoClient_DeleteManyByUID_Call) Run(run func(ctx context.Context, keys []dynamo.Keys, uid string)) *mockDynamoClient_DeleteManyByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dynamo.Keys), args[2].(string))
	})
	return _c
}

func (_c *mockDynamoClient_DeleteManyByUID_Call) Return(_a0 error) *mockDynamoClient_DeleteManyByUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamoClient_DeleteManyByUID_Call) RunAndReturn(run func(context.Context, []dynamo.Keys, string) error) *mockDynamoClient_DeleteManyByUID_Call {
	_c.Call.Return(run)
	return _c
}

// Move provides a mock function with given fields: ctx, oldKeys, value
func (_m *mockDynamoClient) Move(ctx context.Context, oldKeys dynamo.Keys, value any) error {
	ret := _m.Called(ctx, oldKeys, value)

	if len(ret) == 0 {
		panic("no return value specified for Move")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dynamo.Keys, any) error); ok {
		r0 = rf(ctx, oldKeys, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamoClient_Move_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Move'
type mockDynamoClient_Move_Call struct {
	*mock.Call
}

// Move is a helper method to define mock.On call
//   - ctx context.Context
//   - oldKeys dynamo.Keys
//   - value any
func (_e *mockDynamoClient_Expecter) Move(ctx interface{}, oldKeys interface{}, value interface{}) *mockDynamoClient_Move_Call {
	return &mockDynamoClient_Move_Call{Call: _e.mock.On("Move", ctx, oldKeys, value)}
}

func (_c *mockDynamoClient_Move_Call) Run(run func(ctx context.Context, oldKeys dynamo.Keys, value any)) *mockDynamoClient_Move_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dynamo.Keys), args[2].(any))
	})
	return _c
}

func (_c *mockDynamoClient_Move_Call) Return(_a0 error) *mockDynamoClient_Move_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamoClient_Move_Call) RunAndReturn(run func(context.Context, dynamo.Keys, any) error) *mockDynamoClient_Move_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, v
func (_m *mockDynamoClient) Put(ctx context.Context, v interface{}) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamoClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type mockDynamoClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - v interface{}
func (_e *mockDynamoClient_Expecter) Put(ctx interface{}, v interface{}) *mockDynamoClient_Put_Call {
	return &mockDynamoClient_Put_Call{Call: _e.mock.On("Put", ctx, v)}
}

func (_c *mockDynamoClient_Put_Call) Run(run func(ctx context.Context, v interface{})) *mockDynamoClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *mockDynamoClient_Put_Call) Return(_a0 error) *mockDynamoClient_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamoClient_Put_Call) RunAndReturn(run func(context.Context, interface{}) error) *mockDynamoClient_Put_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDynamoClient creates a new instance of mockDynamoClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDynamoClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDynamoClient {
	mock := &mockDynamoClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
