// Code generated by mockery. DO NOT EDIT.

package scheduled

import (
	context "context"

	attorneydata "github.com/ministryofjustice/opg-modernising-lpa/internal/attorney/attorneydata"

	mock "github.com/stretchr/testify/mock"
)

// mockAttorneyStore is an autogenerated mock type for the AttorneyStore type
type mockAttorneyStore struct {
	mock.Mock
}

type mockAttorneyStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockAttorneyStore) EXPECT() *mockAttorneyStore_Expecter {
	return &mockAttorneyStore_Expecter{mock: &_m.Mock}
}

// All provides a mock function with given fields: ctx, lpaUID
func (_m *mockAttorneyStore) All(ctx context.Context, lpaUID string) ([]*attorneydata.Provided, error) {
	ret := _m.Called(ctx, lpaUID)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*attorneydata.Provided
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*attorneydata.Provided, error)); ok {
		return rf(ctx, lpaUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*attorneydata.Provided); ok {
		r0 = rf(ctx, lpaUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*attorneydata.Provided)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, lpaUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockAttorneyStore_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type mockAttorneyStore_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - lpaUID string
func (_e *mockAttorneyStore_Expecter) All(ctx interface{}, lpaUID interface{}) *mockAttorneyStore_All_Call {
	return &mockAttorneyStore_All_Call{Call: _e.mock.On("All", ctx, lpaUID)}
}

func (_c *mockAttorneyStore_All_Call) Run(run func(ctx context.Context, lpaUID string)) *mockAttorneyStore_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockAttorneyStore_All_Call) Return(_a0 []*attorneydata.Provided, _a1 error) *mockAttorneyStore_All_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockAttorneyStore_All_Call) RunAndReturn(run func(context.Context, string) ([]*attorneydata.Provided, error)) *mockAttorneyStore_All_Call {
	_c.Call.Return(run)
	return _c
}

// newMockAttorneyStore creates a new instance of mockAttorneyStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockAttorneyStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockAttorneyStore {
	mock := &mockAttorneyStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
