// Code generated by mockery v2.42.2. DO NOT EDIT.

package attorney

import (
	context "context"

	page "github.com/ministryofjustice/opg-modernising-lpa/internal/page"
	mock "github.com/stretchr/testify/mock"

	temporary "github.com/ministryofjustice/opg-modernising-lpa/internal/temporary"
)

// mockDashboardStore is an autogenerated mock type for the DashboardStore type
type mockDashboardStore struct {
	mock.Mock
}

type mockDashboardStore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDashboardStore) EXPECT() *mockDashboardStore_Expecter {
	return &mockDashboardStore_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function with given fields: ctx
func (_m *mockDashboardStore) GetAll(ctx context.Context) ([]page.LpaAndActorTasks, []page.LpaAndActorTasks, []page.LpaAndActorTasks, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []page.LpaAndActorTasks
	var r1 []page.LpaAndActorTasks
	var r2 []page.LpaAndActorTasks
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]page.LpaAndActorTasks, []page.LpaAndActorTasks, []page.LpaAndActorTasks, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []page.LpaAndActorTasks); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]page.LpaAndActorTasks)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) []page.LpaAndActorTasks); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]page.LpaAndActorTasks)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context) []page.LpaAndActorTasks); ok {
		r2 = rf(ctx)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]page.LpaAndActorTasks)
		}
	}

	if rf, ok := ret.Get(3).(func(context.Context) error); ok {
		r3 = rf(ctx)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// mockDashboardStore_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type mockDashboardStore_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockDashboardStore_Expecter) GetAll(ctx interface{}) *mockDashboardStore_GetAll_Call {
	return &mockDashboardStore_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *mockDashboardStore_GetAll_Call) Run(run func(ctx context.Context)) *mockDashboardStore_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockDashboardStore_GetAll_Call) Return(donor []page.LpaAndActorTasks, attorney []page.LpaAndActorTasks, certificateProvider []page.LpaAndActorTasks, err error) *mockDashboardStore_GetAll_Call {
	_c.Call.Return(donor, attorney, certificateProvider, err)
	return _c
}

func (_c *mockDashboardStore_GetAll_Call) RunAndReturn(run func(context.Context) ([]page.LpaAndActorTasks, []page.LpaAndActorTasks, []page.LpaAndActorTasks, error)) *mockDashboardStore_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// SubExistsForActorType provides a mock function with given fields: ctx, sub, actorType
func (_m *mockDashboardStore) SubExistsForActorType(ctx context.Context, sub string, actorType temporary.ActorType) (bool, error) {
	ret := _m.Called(ctx, sub, actorType)

	if len(ret) == 0 {
		panic("no return value specified for SubExistsForActorType")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, temporary.ActorType) (bool, error)); ok {
		return rf(ctx, sub, actorType)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, temporary.ActorType) bool); ok {
		r0 = rf(ctx, sub, actorType)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, temporary.ActorType) error); ok {
		r1 = rf(ctx, sub, actorType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDashboardStore_SubExistsForActorType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubExistsForActorType'
type mockDashboardStore_SubExistsForActorType_Call struct {
	*mock.Call
}

// SubExistsForActorType is a helper method to define mock.On call
//   - ctx context.Context
//   - sub string
//   - actorType temporary.ActorType
func (_e *mockDashboardStore_Expecter) SubExistsForActorType(ctx interface{}, sub interface{}, actorType interface{}) *mockDashboardStore_SubExistsForActorType_Call {
	return &mockDashboardStore_SubExistsForActorType_Call{Call: _e.mock.On("SubExistsForActorType", ctx, sub, actorType)}
}

func (_c *mockDashboardStore_SubExistsForActorType_Call) Run(run func(ctx context.Context, sub string, actorType temporary.ActorType)) *mockDashboardStore_SubExistsForActorType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(temporary.ActorType))
	})
	return _c
}

func (_c *mockDashboardStore_SubExistsForActorType_Call) Return(_a0 bool, _a1 error) *mockDashboardStore_SubExistsForActorType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDashboardStore_SubExistsForActorType_Call) RunAndReturn(run func(context.Context, string, temporary.ActorType) (bool, error)) *mockDashboardStore_SubExistsForActorType_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDashboardStore creates a new instance of mockDashboardStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDashboardStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDashboardStore {
	mock := &mockDashboardStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
