// Code generated by mockery. DO NOT EDIT.

package forms

import (
	url "net/url"

	mock "github.com/stretchr/testify/mock"
)

// mockParseable is an autogenerated mock type for the Parseable type
type mockParseable struct {
	mock.Mock
}

type mockParseable_Expecter struct {
	mock *mock.Mock
}

func (_m *mockParseable) EXPECT() *mockParseable_Expecter {
	return &mockParseable_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: _a0
func (_m *mockParseable) Parse(_a0 url.Values) {
	_m.Called(_a0)
}

// mockParseable_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type mockParseable_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - _a0 url.Values
func (_e *mockParseable_Expecter) Parse(_a0 interface{}) *mockParseable_Parse_Call {
	return &mockParseable_Parse_Call{Call: _e.mock.On("Parse", _a0)}
}

func (_c *mockParseable_Parse_Call) Run(run func(_a0 url.Values)) *mockParseable_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(url.Values))
	})
	return _c
}

func (_c *mockParseable_Parse_Call) Return() *mockParseable_Parse_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockParseable_Parse_Call) RunAndReturn(run func(url.Values)) *mockParseable_Parse_Call {
	_c.Run(run)
	return _c
}

// field provides a mock function with no fields
func (_m *mockParseable) field() Field {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for field")
	}

	var r0 Field
	if rf, ok := ret.Get(0).(func() Field); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(Field)
	}

	return r0
}

// mockParseable_field_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'field'
type mockParseable_field_Call struct {
	*mock.Call
}

// field is a helper method to define mock.On call
func (_e *mockParseable_Expecter) field() *mockParseable_field_Call {
	return &mockParseable_field_Call{Call: _e.mock.On("field")}
}

func (_c *mockParseable_field_Call) Run(run func()) *mockParseable_field_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockParseable_field_Call) Return(_a0 Field) *mockParseable_field_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockParseable_field_Call) RunAndReturn(run func() Field) *mockParseable_field_Call {
	_c.Call.Return(run)
	return _c
}

// newMockParseable creates a new instance of mockParseable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockParseable(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockParseable {
	mock := &mockParseable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
