plugin: openapi
specFile: https://raw.githubusercontent.com/ministryofjustice/opg-data-lpa-uid/main/docs/openapi/openapi.yaml

validation:
  request: true

resources:
  - path: "/cases"
    method: POST
    response:
      scriptFile: uid.js
