// Code generated by mockery v2.42.0. DO NOT EDIT.

package main

import (
	context "context"

	dynamo "github.com/ministryofjustice/opg-modernising-lpa/internal/dynamo"
	mock "github.com/stretchr/testify/mock"

	types "github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
)

// mockDynamodbClient is an autogenerated mock type for the dynamodbClient type
type mockDynamodbClient struct {
	mock.Mock
}

type mockDynamodbClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDynamodbClient) EXPECT() *mockDynamodbClient_Expecter {
	return &mockDynamodbClient_Expecter{mock: &_m.Mock}
}

// AllByKeys provides a mock function with given fields: ctx, keys
func (_m *mockDynamodbClient) AllByKeys(ctx context.Context, keys []dynamo.Key) ([]map[string]types.AttributeValue, error) {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for AllByKeys")
	}

	var r0 []map[string]types.AttributeValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []dynamo.Key) ([]map[string]types.AttributeValue, error)); ok {
		return rf(ctx, keys)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []dynamo.Key) []map[string]types.AttributeValue); ok {
		r0 = rf(ctx, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]types.AttributeValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []dynamo.Key) error); ok {
		r1 = rf(ctx, keys)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDynamodbClient_AllByKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllByKeys'
type mockDynamodbClient_AllByKeys_Call struct {
	*mock.Call
}

// AllByKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []dynamo.Key
func (_e *mockDynamodbClient_Expecter) AllByKeys(ctx interface{}, keys interface{}) *mockDynamodbClient_AllByKeys_Call {
	return &mockDynamodbClient_AllByKeys_Call{Call: _e.mock.On("AllByKeys", ctx, keys)}
}

func (_c *mockDynamodbClient_AllByKeys_Call) Run(run func(ctx context.Context, keys []dynamo.Key)) *mockDynamodbClient_AllByKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dynamo.Key))
	})
	return _c
}

func (_c *mockDynamodbClient_AllByKeys_Call) Return(_a0 []map[string]types.AttributeValue, _a1 error) *mockDynamodbClient_AllByKeys_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDynamodbClient_AllByKeys_Call) RunAndReturn(run func(context.Context, []dynamo.Key) ([]map[string]types.AttributeValue, error)) *mockDynamodbClient_AllByKeys_Call {
	_c.Call.Return(run)
	return _c
}

// AllByPartialSK provides a mock function with given fields: ctx, pk, partialSK, v
func (_m *mockDynamodbClient) AllByPartialSK(ctx context.Context, pk string, partialSK string, v interface{}) error {
	ret := _m.Called(ctx, pk, partialSK, v)

	if len(ret) == 0 {
		panic("no return value specified for AllByPartialSK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, pk, partialSK, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_AllByPartialSK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllByPartialSK'
type mockDynamodbClient_AllByPartialSK_Call struct {
	*mock.Call
}

// AllByPartialSK is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - partialSK string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) AllByPartialSK(ctx interface{}, pk interface{}, partialSK interface{}, v interface{}) *mockDynamodbClient_AllByPartialSK_Call {
	return &mockDynamodbClient_AllByPartialSK_Call{Call: _e.mock.On("AllByPartialSK", ctx, pk, partialSK, v)}
}

func (_c *mockDynamodbClient_AllByPartialSK_Call) Run(run func(ctx context.Context, pk string, partialSK string, v interface{})) *mockDynamodbClient_AllByPartialSK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_AllByPartialSK_Call) Return(_a0 error) *mockDynamodbClient_AllByPartialSK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_AllByPartialSK_Call) RunAndReturn(run func(context.Context, string, string, interface{}) error) *mockDynamodbClient_AllByPartialSK_Call {
	_c.Call.Return(run)
	return _c
}

// AllBySK provides a mock function with given fields: ctx, sk, v
func (_m *mockDynamodbClient) AllBySK(ctx context.Context, sk string, v interface{}) error {
	ret := _m.Called(ctx, sk, v)

	if len(ret) == 0 {
		panic("no return value specified for AllBySK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, sk, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_AllBySK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllBySK'
type mockDynamodbClient_AllBySK_Call struct {
	*mock.Call
}

// AllBySK is a helper method to define mock.On call
//   - ctx context.Context
//   - sk string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) AllBySK(ctx interface{}, sk interface{}, v interface{}) *mockDynamodbClient_AllBySK_Call {
	return &mockDynamodbClient_AllBySK_Call{Call: _e.mock.On("AllBySK", ctx, sk, v)}
}

func (_c *mockDynamodbClient_AllBySK_Call) Run(run func(ctx context.Context, sk string, v interface{})) *mockDynamodbClient_AllBySK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_AllBySK_Call) Return(_a0 error) *mockDynamodbClient_AllBySK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_AllBySK_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *mockDynamodbClient_AllBySK_Call {
	_c.Call.Return(run)
	return _c
}

// AllKeysByPK provides a mock function with given fields: ctx, pk
func (_m *mockDynamodbClient) AllKeysByPK(ctx context.Context, pk string) ([]dynamo.Key, error) {
	ret := _m.Called(ctx, pk)

	if len(ret) == 0 {
		panic("no return value specified for AllKeysByPK")
	}

	var r0 []dynamo.Key
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]dynamo.Key, error)); ok {
		return rf(ctx, pk)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []dynamo.Key); ok {
		r0 = rf(ctx, pk)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dynamo.Key)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pk)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDynamodbClient_AllKeysByPK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllKeysByPK'
type mockDynamodbClient_AllKeysByPK_Call struct {
	*mock.Call
}

// AllKeysByPK is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
func (_e *mockDynamodbClient_Expecter) AllKeysByPK(ctx interface{}, pk interface{}) *mockDynamodbClient_AllKeysByPK_Call {
	return &mockDynamodbClient_AllKeysByPK_Call{Call: _e.mock.On("AllKeysByPK", ctx, pk)}
}

func (_c *mockDynamodbClient_AllKeysByPK_Call) Run(run func(ctx context.Context, pk string)) *mockDynamodbClient_AllKeysByPK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDynamodbClient_AllKeysByPK_Call) Return(_a0 []dynamo.Key, _a1 error) *mockDynamodbClient_AllKeysByPK_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDynamodbClient_AllKeysByPK_Call) RunAndReturn(run func(context.Context, string) ([]dynamo.Key, error)) *mockDynamodbClient_AllKeysByPK_Call {
	_c.Call.Return(run)
	return _c
}

// BatchPut provides a mock function with given fields: ctx, items
func (_m *mockDynamodbClient) BatchPut(ctx context.Context, items []interface{}) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BatchPut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []interface{}) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_BatchPut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchPut'
type mockDynamodbClient_BatchPut_Call struct {
	*mock.Call
}

// BatchPut is a helper method to define mock.On call
//   - ctx context.Context
//   - items []interface{}
func (_e *mockDynamodbClient_Expecter) BatchPut(ctx interface{}, items interface{}) *mockDynamodbClient_BatchPut_Call {
	return &mockDynamodbClient_BatchPut_Call{Call: _e.mock.On("BatchPut", ctx, items)}
}

func (_c *mockDynamodbClient_BatchPut_Call) Run(run func(ctx context.Context, items []interface{})) *mockDynamodbClient_BatchPut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_BatchPut_Call) Return(_a0 error) *mockDynamodbClient_BatchPut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_BatchPut_Call) RunAndReturn(run func(context.Context, []interface{}) error) *mockDynamodbClient_BatchPut_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, v
func (_m *mockDynamodbClient) Create(ctx context.Context, v interface{}) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockDynamodbClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) Create(ctx interface{}, v interface{}) *mockDynamodbClient_Create_Call {
	return &mockDynamodbClient_Create_Call{Call: _e.mock.On("Create", ctx, v)}
}

func (_c *mockDynamodbClient_Create_Call) Run(run func(ctx context.Context, v interface{})) *mockDynamodbClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_Create_Call) Return(_a0 error) *mockDynamodbClient_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_Create_Call) RunAndReturn(run func(context.Context, interface{}) error) *mockDynamodbClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKeys provides a mock function with given fields: ctx, keys
func (_m *mockDynamodbClient) DeleteKeys(ctx context.Context, keys []dynamo.Key) error {
	ret := _m.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKeys")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []dynamo.Key) error); ok {
		r0 = rf(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_DeleteKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKeys'
type mockDynamodbClient_DeleteKeys_Call struct {
	*mock.Call
}

// DeleteKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []dynamo.Key
func (_e *mockDynamodbClient_Expecter) DeleteKeys(ctx interface{}, keys interface{}) *mockDynamodbClient_DeleteKeys_Call {
	return &mockDynamodbClient_DeleteKeys_Call{Call: _e.mock.On("DeleteKeys", ctx, keys)}
}

func (_c *mockDynamodbClient_DeleteKeys_Call) Run(run func(ctx context.Context, keys []dynamo.Key)) *mockDynamodbClient_DeleteKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]dynamo.Key))
	})
	return _c
}

func (_c *mockDynamodbClient_DeleteKeys_Call) Return(_a0 error) *mockDynamodbClient_DeleteKeys_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_DeleteKeys_Call) RunAndReturn(run func(context.Context, []dynamo.Key) error) *mockDynamodbClient_DeleteKeys_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOne provides a mock function with given fields: ctx, pk, sk
func (_m *mockDynamodbClient) DeleteOne(ctx context.Context, pk string, sk string) error {
	ret := _m.Called(ctx, pk, sk)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOne")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, pk, sk)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_DeleteOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOne'
type mockDynamodbClient_DeleteOne_Call struct {
	*mock.Call
}

// DeleteOne is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - sk string
func (_e *mockDynamodbClient_Expecter) DeleteOne(ctx interface{}, pk interface{}, sk interface{}) *mockDynamodbClient_DeleteOne_Call {
	return &mockDynamodbClient_DeleteOne_Call{Call: _e.mock.On("DeleteOne", ctx, pk, sk)}
}

func (_c *mockDynamodbClient_DeleteOne_Call) Run(run func(ctx context.Context, pk string, sk string)) *mockDynamodbClient_DeleteOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *mockDynamodbClient_DeleteOne_Call) Return(_a0 error) *mockDynamodbClient_DeleteOne_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_DeleteOne_Call) RunAndReturn(run func(context.Context, string, string) error) *mockDynamodbClient_DeleteOne_Call {
	_c.Call.Return(run)
	return _c
}

// LatestForActor provides a mock function with given fields: ctx, sk, v
func (_m *mockDynamodbClient) LatestForActor(ctx context.Context, sk string, v interface{}) error {
	ret := _m.Called(ctx, sk, v)

	if len(ret) == 0 {
		panic("no return value specified for LatestForActor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, sk, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_LatestForActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LatestForActor'
type mockDynamodbClient_LatestForActor_Call struct {
	*mock.Call
}

// LatestForActor is a helper method to define mock.On call
//   - ctx context.Context
//   - sk string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) LatestForActor(ctx interface{}, sk interface{}, v interface{}) *mockDynamodbClient_LatestForActor_Call {
	return &mockDynamodbClient_LatestForActor_Call{Call: _e.mock.On("LatestForActor", ctx, sk, v)}
}

func (_c *mockDynamodbClient_LatestForActor_Call) Run(run func(ctx context.Context, sk string, v interface{})) *mockDynamodbClient_LatestForActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_LatestForActor_Call) Return(_a0 error) *mockDynamodbClient_LatestForActor_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_LatestForActor_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *mockDynamodbClient_LatestForActor_Call {
	_c.Call.Return(run)
	return _c
}

// One provides a mock function with given fields: ctx, pk, sk, v
func (_m *mockDynamodbClient) One(ctx context.Context, pk string, sk string, v interface{}) error {
	ret := _m.Called(ctx, pk, sk, v)

	if len(ret) == 0 {
		panic("no return value specified for One")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, pk, sk, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_One_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'One'
type mockDynamodbClient_One_Call struct {
	*mock.Call
}

// One is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - sk string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) One(ctx interface{}, pk interface{}, sk interface{}, v interface{}) *mockDynamodbClient_One_Call {
	return &mockDynamodbClient_One_Call{Call: _e.mock.On("One", ctx, pk, sk, v)}
}

func (_c *mockDynamodbClient_One_Call) Run(run func(ctx context.Context, pk string, sk string, v interface{})) *mockDynamodbClient_One_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_One_Call) Return(_a0 error) *mockDynamodbClient_One_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_One_Call) RunAndReturn(run func(context.Context, string, string, interface{}) error) *mockDynamodbClient_One_Call {
	_c.Call.Return(run)
	return _c
}

// OneByPartialSK provides a mock function with given fields: ctx, pk, partialSK, v
func (_m *mockDynamodbClient) OneByPartialSK(ctx context.Context, pk string, partialSK string, v interface{}) error {
	ret := _m.Called(ctx, pk, partialSK, v)

	if len(ret) == 0 {
		panic("no return value specified for OneByPartialSK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, interface{}) error); ok {
		r0 = rf(ctx, pk, partialSK, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_OneByPartialSK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OneByPartialSK'
type mockDynamodbClient_OneByPartialSK_Call struct {
	*mock.Call
}

// OneByPartialSK is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - partialSK string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) OneByPartialSK(ctx interface{}, pk interface{}, partialSK interface{}, v interface{}) *mockDynamodbClient_OneByPartialSK_Call {
	return &mockDynamodbClient_OneByPartialSK_Call{Call: _e.mock.On("OneByPartialSK", ctx, pk, partialSK, v)}
}

func (_c *mockDynamodbClient_OneByPartialSK_Call) Run(run func(ctx context.Context, pk string, partialSK string, v interface{})) *mockDynamodbClient_OneByPartialSK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_OneByPartialSK_Call) Return(_a0 error) *mockDynamodbClient_OneByPartialSK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_OneByPartialSK_Call) RunAndReturn(run func(context.Context, string, string, interface{}) error) *mockDynamodbClient_OneByPartialSK_Call {
	_c.Call.Return(run)
	return _c
}

// OneBySK provides a mock function with given fields: ctx, sk, v
func (_m *mockDynamodbClient) OneBySK(ctx context.Context, sk string, v interface{}) error {
	ret := _m.Called(ctx, sk, v)

	if len(ret) == 0 {
		panic("no return value specified for OneBySK")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, sk, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_OneBySK_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OneBySK'
type mockDynamodbClient_OneBySK_Call struct {
	*mock.Call
}

// OneBySK is a helper method to define mock.On call
//   - ctx context.Context
//   - sk string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) OneBySK(ctx interface{}, sk interface{}, v interface{}) *mockDynamodbClient_OneBySK_Call {
	return &mockDynamodbClient_OneBySK_Call{Call: _e.mock.On("OneBySK", ctx, sk, v)}
}

func (_c *mockDynamodbClient_OneBySK_Call) Run(run func(ctx context.Context, sk string, v interface{})) *mockDynamodbClient_OneBySK_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_OneBySK_Call) Return(_a0 error) *mockDynamodbClient_OneBySK_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_OneBySK_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *mockDynamodbClient_OneBySK_Call {
	_c.Call.Return(run)
	return _c
}

// OneByUID provides a mock function with given fields: ctx, uid, v
func (_m *mockDynamodbClient) OneByUID(ctx context.Context, uid string, v interface{}) error {
	ret := _m.Called(ctx, uid, v)

	if len(ret) == 0 {
		panic("no return value specified for OneByUID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) error); ok {
		r0 = rf(ctx, uid, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_OneByUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OneByUID'
type mockDynamodbClient_OneByUID_Call struct {
	*mock.Call
}

// OneByUID is a helper method to define mock.On call
//   - ctx context.Context
//   - uid string
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) OneByUID(ctx interface{}, uid interface{}, v interface{}) *mockDynamodbClient_OneByUID_Call {
	return &mockDynamodbClient_OneByUID_Call{Call: _e.mock.On("OneByUID", ctx, uid, v)}
}

func (_c *mockDynamodbClient_OneByUID_Call) Run(run func(ctx context.Context, uid string, v interface{})) *mockDynamodbClient_OneByUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_OneByUID_Call) Return(_a0 error) *mockDynamodbClient_OneByUID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_OneByUID_Call) RunAndReturn(run func(context.Context, string, interface{}) error) *mockDynamodbClient_OneByUID_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: ctx, v
func (_m *mockDynamodbClient) Put(ctx context.Context, v interface{}) error {
	ret := _m.Called(ctx, v)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) error); ok {
		r0 = rf(ctx, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type mockDynamodbClient_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - v interface{}
func (_e *mockDynamodbClient_Expecter) Put(ctx interface{}, v interface{}) *mockDynamodbClient_Put_Call {
	return &mockDynamodbClient_Put_Call{Call: _e.mock.On("Put", ctx, v)}
}

func (_c *mockDynamodbClient_Put_Call) Run(run func(ctx context.Context, v interface{})) *mockDynamodbClient_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *mockDynamodbClient_Put_Call) Return(_a0 error) *mockDynamodbClient_Put_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_Put_Call) RunAndReturn(run func(context.Context, interface{}) error) *mockDynamodbClient_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, pk, sk, values, expression
func (_m *mockDynamodbClient) Update(ctx context.Context, pk string, sk string, values map[string]types.AttributeValue, expression string) error {
	ret := _m.Called(ctx, pk, sk, values, expression)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]types.AttributeValue, string) error); ok {
		r0 = rf(ctx, pk, sk, values, expression)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDynamodbClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockDynamodbClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - sk string
//   - values map[string]types.AttributeValue
//   - expression string
func (_e *mockDynamodbClient_Expecter) Update(ctx interface{}, pk interface{}, sk interface{}, values interface{}, expression interface{}) *mockDynamodbClient_Update_Call {
	return &mockDynamodbClient_Update_Call{Call: _e.mock.On("Update", ctx, pk, sk, values, expression)}
}

func (_c *mockDynamodbClient_Update_Call) Run(run func(ctx context.Context, pk string, sk string, values map[string]types.AttributeValue, expression string)) *mockDynamodbClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]types.AttributeValue), args[4].(string))
	})
	return _c
}

func (_c *mockDynamodbClient_Update_Call) Return(_a0 error) *mockDynamodbClient_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDynamodbClient_Update_Call) RunAndReturn(run func(context.Context, string, string, map[string]types.AttributeValue, string) error) *mockDynamodbClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReturn provides a mock function with given fields: ctx, pk, sk, values, expression
func (_m *mockDynamodbClient) UpdateReturn(ctx context.Context, pk string, sk string, values map[string]types.AttributeValue, expression string) (map[string]types.AttributeValue, error) {
	ret := _m.Called(ctx, pk, sk, values, expression)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReturn")
	}

	var r0 map[string]types.AttributeValue
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]types.AttributeValue, string) (map[string]types.AttributeValue, error)); ok {
		return rf(ctx, pk, sk, values, expression)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]types.AttributeValue, string) map[string]types.AttributeValue); ok {
		r0 = rf(ctx, pk, sk, values, expression)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]types.AttributeValue)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]types.AttributeValue, string) error); ok {
		r1 = rf(ctx, pk, sk, values, expression)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDynamodbClient_UpdateReturn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReturn'
type mockDynamodbClient_UpdateReturn_Call struct {
	*mock.Call
}

// UpdateReturn is a helper method to define mock.On call
//   - ctx context.Context
//   - pk string
//   - sk string
//   - values map[string]types.AttributeValue
//   - expression string
func (_e *mockDynamodbClient_Expecter) UpdateReturn(ctx interface{}, pk interface{}, sk interface{}, values interface{}, expression interface{}) *mockDynamodbClient_UpdateReturn_Call {
	return &mockDynamodbClient_UpdateReturn_Call{Call: _e.mock.On("UpdateReturn", ctx, pk, sk, values, expression)}
}

func (_c *mockDynamodbClient_UpdateReturn_Call) Run(run func(ctx context.Context, pk string, sk string, values map[string]types.AttributeValue, expression string)) *mockDynamodbClient_UpdateReturn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]types.AttributeValue), args[4].(string))
	})
	return _c
}

func (_c *mockDynamodbClient_UpdateReturn_Call) Return(_a0 map[string]types.AttributeValue, _a1 error) *mockDynamodbClient_UpdateReturn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDynamodbClient_UpdateReturn_Call) RunAndReturn(run func(context.Context, string, string, map[string]types.AttributeValue, string) (map[string]types.AttributeValue, error)) *mockDynamodbClient_UpdateReturn_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDynamodbClient creates a new instance of mockDynamodbClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDynamodbClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDynamodbClient {
	mock := &mockDynamodbClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
