name: "[Job] check healthcheck endpoints"

on:
  workflow_call:
    inputs:
      base_url:
        description: "Environment URL to target for testing"
        required: false
        type: string
        default: http://localhost:5050
      environment_config_json:
        required: false
        type: string
      ingress_management_oidc_role_arn:
        description: "ARN for OIDC role to assume"
        required: true
        type: string
    secrets:
      github_access_token:
        description: "Github Token"
        required: true

defaults:
  run:
    shell: bash

jobs:
  run_ui_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          ref: ${{ inputs.checkout_tag }}
      - name: Manage Ingress/Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: ${{ inputs.ingress_management_oidc_role_arn }}
          aws-region: eu-west-1
          role-duration-seconds: 900
          role-session-name: OPGModernisingLPATerraformGithubActionTestInfra
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"
          check-latest: true
      - run: pip install -r ./scripts/ci_ingress/requirements.txt
      - name: add_ingress
        run: python ./scripts/ci_ingress/ci_ingress.py ${{
          inputs.environment_config_json}} --add
      - name: Check environment is available
        run: |
          service_response=$(curl --write-out %{http_code} --silent --output /dev/null ${{ inputs.base_url }}/health-check/service)
          [[ $service_response == 200 ]] || (echo "Error with service health check. HTTP status: ${service_response}" && exit 1)
          dependency_response=$(curl --write-out %{http_code} --silent --output /dev/null ${{ inputs.base_url }}/health-check/dependency)
          [[ $dependency_response == 200 ]] || (echo "Error with service health check. HTTP status: ${dependency_response}" && exit 1)
