name: "[WD] Scan production containers for vulnerabilities"

on:
  workflow_dispatch:
  schedule:
    - cron: "30 9 * * 1"

defaults:
  run:
    shell: bash

permissions:
  id-token: write


jobs:
  pull_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::311462405659:role/modernising-lpa-github-actions-ssm-get-parameter
          role-duration-seconds: 900
          role-session-name: GithubActionsSSMGetParameter
      - name: Pull production tag
        id: pull_tag
        run: |
          key="/modernising-lpa/container-version/production"
          value=$(aws ssm get-parameter --name "$key" --query 'Parameter.Value' --output text)
          echo "Using $key: $value"
          echo "tag=${value}" >> $GITHUB_OUTPUT
          echo "env=${key}" >> $GITHUB_OUTPUT
    outputs:
      docker_tag: ${{ steps.pull_tag.outputs.tag }}
      tag_from: ${{ steps.pull_tag.outputs.env }}
  trivy_scan_report:
    needs: pull_tags
    strategy:
      fail-fast: false
      matrix:
        include:
          - ecr_repository: modernising-lpa/app
            name: app
            path: ./docker/mlpa/Dockerfile
            trivyignores: ./docker/mlpa/.trivyignore.yaml
            platforms: linux/amd64
          - ecr_repository: modernising-lpa/create-s3-batch-replication-job
            name: create-s3-batch-replication-job
            path: ./docker/create-s3-replication-job/Dockerfile
            trivyignores: ./docker/create-s3-replication-job/.trivyignore.yaml
            platforms: linux/amd64
          - ecr_repository: modernising-lpa/event-received
            name: event-received
            path: ./docker/event-received/Dockerfile
            trivyignores: ./docker/event-received/.trivyignore.yaml
            platforms: linux/amd64
          - ecr_repository: modernising-lpa/schedule-runner
            name: schedule-runner
            path: ./docker/schedule-runner/Dockerfile
            trivyignores: ./docker/schedule-runner/.trivyignore.yaml
            platforms: linux/amd64

    runs-on: ubuntu-latest
    name: ${{ matrix.ecr_repository }}
    steps:
      - name: Run Against Image/Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::311462405659:role/modernising-lpa-github-actions-image-scan
          role-duration-seconds: 900
          role-session-name: GithubActionsECRPullMLPAB
      - name: ECR Login
        id: login_ecr
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
        with:
          mask-password: true
          registries: 311462405659
      - name: check file exists
        if: ${{ hashFiles('trivy-results.txt') != '' }}
        run: rm -f trivy-results.txt
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Trivy Image Vulnerability Scanner for ${{ matrix.ecr_repository }}
        id: trivy_scan
        uses: aquasecurity/trivy-action@f9424c10c36e288d5fa79bd3dfd1aeb2d6eae808 # 0.33.0
        env:
          TRIVY_DB_REPOSITORY: ${{ steps.login_ecr.outputs.registry }}/trivy-db-public-ecr/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: ${{ steps.login_ecr.outputs.registry }}/trivy-db-public-ecr/aquasecurity/trivy-java-db:1
          TRIVY_DISABLE_VEX_NOTICE: true
          TRIVY_IGNOREFILE: ${{ matrix.trivyignores }}
        with:
          scan-type: 'image'
          scanners: 'vuln'
          image-ref: ${{ steps.login_ecr.outputs.registry }}/${{ matrix.ecr_repository }}:${{ needs.pull_tags.outputs.docker_tag }}
          severity: 'HIGH,CRITICAL'
          format: 'table'
          output: '${{ matrix.name }}-trivy-results.txt'
          exit-code: 1
      - name: Unset AWS credentials
        if: always()
        run: |
          unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
      - name: Publish Trivy Output to Summary
        if: always()
        run: |
          if [[ -s ${{ matrix.name }}-trivy-results.txt ]]; then
            {
              echo "### Security Output ${{ matrix.ecr_repository }}:${{ needs.pull_tags.outputs.docker_tag }}"
              echo "<details><summary>Click to expand</summary>"
              echo ""
              echo '```text'
              cat ${{ matrix.name }}-trivy-results.txt
              echo '```'
              echo "</details>"
            } >> $GITHUB_STEP_SUMMARY
          fi
      - name: Post to a Slack channel
        if: always() && steps.trivy_scan.conclusion == 'failure'
        id: slack
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: opg-mlpa-dev
            text: "Production Image Scan Findings"
            blocks:
              - type: "header"
                text:
                  type: "plain_text"
                  text: ":exclamation: Production Image Scan Findings for ${{ matrix.ecr_repository }}"
                  emoji: true
              - type: "section"
                text:
                  type: "plain_text"
                  text: "Critical or High severity vulnerabilities found in version *${{ needs.pull_tags.outputs.docker_tag }}*"
                  emoji: true
              - type: "actions"
                block_id: action_1
                elements:
                - type: "button"
                  text:
                    type: "plain_text"
                    text: "View Findings Here"
                  url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
