name: "[Job] Lint markdown files"

on:
	workflow_call:

jobs:
	lint-markdown:
  - name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Warn missing markdown lint
        run: echo "::warning title=MISSING-MARKDOWN-LINT::Please add the markdown lint workflow step when an allowed action is available."

# TODO: removed due to github actions non-compliance - add alternative allowed action when available.
