name: "[Job] Run Go integration tests"

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: '^1.20'
          cache-dependency-path: '**/go.sum'
          cache: true

      - name: Run integration tests
        run: |
          docker compose -f docker/docker-compose.yml up -d --wait localstack
          make go-integration-test
