name: "[Job] Post slack message"

on:
  workflow_call:
    inputs:
      payload:
        description: 'For posting a rich message using Block Kit'
        required: true
        type: string
    secrets:
      slack-bot-token:
        description: 'A token passed from the caller workflow'
        required: false

defaults:
  run:
    shell: bash

jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@v2.0.0
      with:
        tag: ${{ needs.pull_tags.outputs.docker_tag}}
        method: chat.postMessage
        token: ${{ secrets.SLACK_BOT_TOKEN }}
        payload: ${{ inputs.payload }}
