name: "[Job] Post slack message"

on:
  workflow_call:
    inputs:
      payload:
        description: 'For posting a rich message using Block Kit'
        required: true
        type: string
    secrets:
      slack-bot-token:
        description: 'A token passed from the caller workflow'
        required: false

defaults:
  run:
    shell: bash

jobs:
  post_to_slack:
    runs-on: ubuntu-latest
    steps:
    - name: Post to a Slack channel
      id: slack
      uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
      with:
        method: chat.postMessage
        token: ${{ secrets.slack-bot-token }}
        payload: ${{ inputs.payload }}
