name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  terraform_account_workflow_development:
    name: TF Plan/Apply Dev Account
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: development
    secrets: inherit

  terraform_account_workflow_production:
    name: TF Plan/Apply Prod Account
    needs: terraform_account_workflow_development
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: production
    secrets: inherit
