name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'web/**'
      - 'codecept/**'
      - 'cypress/**'
      - 'terraform/**'
      - 'scripts/**'
      - '.github/workflows/**'

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  create_tags:
    name: Create Tags
    uses: ./.github/workflows/tags_job.yml

  # go_unit_tests:
  #   name: Run Go unit tests
  #   uses: ./.github/workflows/go-unit-tests.yml

  # docker_build_scan_push:
  #   name: Docker Build, Scan and Push
  #   uses: ./.github/workflows/docker_job.yml
  #   needs: [go_unit_tests, create_tags]
  #   with:
  #     tag: ${{ needs.create_tags.outputs.version_tag }}
  #   secrets: inherit

  # terraform_account_workflow_development:
  #   name: TF Plan Dev Account
  #   uses: ./.github/workflows/terraform_account_job.yml
  #   with:
  #     workspace_name: development
  #   secrets: inherit

  # terraform_account_workflow_preproduction:
  #   name: TF Plan Preprod Account
  #   needs: terraform_account_workflow_development
  #   uses: ./.github/workflows/terraform_account_job.yml
  #   with:
  #     workspace_name: preproduction
  #   secrets: inherit

  # terraform_account_workflow_production:
  #   name: TF Plan Prod Account
  #   needs: terraform_account_workflow_development
  #   uses: ./.github/workflows/terraform_account_job.yml
  #   with:
  #     workspace_name: production
  #   secrets: inherit

  # ui_tests_image:
  #   name: Run Cypress UI Tests On Images
  #   uses: ./.github/workflows/ui_test_job.yml
  #   needs: [docker_build_scan_push, create_tags]
  #   with:
  #     run_against_image: true
  #     tag: ${{ needs.create_tags.outputs.version_tag }}
  #   secrets: inherit

  pr_deploy:
      name: PR Environment Deploy
      needs: [create_tags, docker_build_scan_push, ui_tests_image]
      uses: ./.github/workflows/terraform_environment_job.yml
      with:
        workspace_name: ${{ needs.create_tags.outputs.environment_workspace_name }}
        version_tag: latest
        # version_tag: ${{ needs.create_tags.outputs.version_tag }}
      secrets: inherit

  # ui_tests_pr_env:
  #   name: Run Cypress UI Tests On PR Environment
  #   uses: ./.github/workflows/ui_test_job.yml
  #   needs: [pr_deploy, create_tags]
  #   with:
  #     run_against_image: false
  #     base_url: "https://${{ needs.pr_deploy.outputs.url }}"
  #     tag: ${{ needs.create_tags.outputs.version_tag }}
  #   secrets: inherit

  # always_remove_ingress:
  #   name: Remove CI ingress from environment
  #   if: ${{ always() }}
  #   uses: ./.github/workflows/remove_ingress_job.yml
  #   needs: [ui_tests_pr_env]
  #   secrets: inherit

  # end_of_pr_workflow:
  #   name: End of PR Workflow
  #   if: github.ref != 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: "dev_${{ needs.create_tags.outputs.environment_workspace_name }}"
  #     url: "https://${{ needs.pr_deploy.outputs.url }}"
  #   needs: [pr_deploy, create_tags, ui_tests_pr_env]
  #   steps:
  #     - name: End of PR Workflow
  #       run: |
  #         echo "${{ needs.pr_deploy.outputs.terraform_workspace_name }} PR environment tested, built and deployed"
  #         echo "Tag Deployed: ${{ needs.pr_deploy.outputs.terraform_container_version }}"
  #         echo "URL: https://${{ needs.pr_deploy.outputs.url }}"
