name: "[Workflow] PR"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  security-events: write
  pull-requests: read
  actions: none
  checks: none
  deployments: none
  issues: none
  packages: none
  repository-projects: none
  statuses: none

defaults:
  run:
    shell: bash

jobs:
  terraform_account_workflow_development:
    name: TF Plan Dev Account
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: development
    secrets: inherit

  terraform_account_workflow_preproduction:
    name: TF Plan Preprod Account
    needs: terraform_account_workflow_development
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: preproduction
    secrets: inherit

  terraform_account_workflow_production:
    name: TF Plan Prod Account
    needs: terraform_account_workflow_development
    uses: ./.github/workflows/terraform_account_job.yml
    with:
      workspace_name: production
    secrets: inherit

  pr_deploy:
      name: PR Environment Deploy
      needs: [create_tags]
      uses: ./.github/workflows/terraform_environment_job.yml
      with:
        workspace_name: ${{ needs.create_tags.outputs.environment_workspace_name }}
        version_tag: ${{ needs.create_tags.outputs.version_tag }}
      secrets: inherit
